(() => {
'use strict';
const $ = id => document.getElementById(id);
const STORE='family-tasks:demo:v1', MODE='family-tasks:mode:v1', CONFIG='my-html-tools:firebase-config:v1';
const colors=['#ad3535','#c84b36','#e36438','#ee8542','#f1a44c','#f4bc60','#f1cc78','#f3d891'];
const legacy=new Set(['家','買い物','子ども','その他','家事','子育て','住宅','仕事']);
const state={mode:'demo',tasks:[],user:null,family:null,sdk:null,connection:null,familyUnsub:null,taskUnsub:null,authUnsub:null,metadata:null,status:'open',editing:null,busy:false,blocked:false,gesture:null,pull:null,blockClickUntil:0};
const get=k=>{try{return localStorage.getItem(k);}catch(_){return null;}};
const set=(k,v)=>{try{localStorage.setItem(k,v);return true;}catch(_){return false;}};
const uid=()=>state.mode==='demo'?'demo-me':state.user?.uid||'';
const uuid=()=>globalThis.crypto?.randomUUID?.()||`task-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const rank=t=>Number.isFinite(t.sortOrder)?t.sortOrder:-t.createdAt;
const compare=(a,b)=>rank(a)-rank(b)||a.id.localeCompare(b.id);
const all=()=>state.tasks.filter(t=>t.scope==='shared');
const visible=()=>all().filter(t=>state.status==='all'||(state.status==='open'?!t.done:t.done)).sort(compare);
const validDate=value=>{if(value==='')return true;if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const [y,m,d]=value.split('-').map(Number),a=new Date(y,m-1,d,12);return y>=1900&&y<=9999&&a.getFullYear()===y&&a.getMonth()+1===m&&a.getDate()===d;};
function validTask(t){return t&&typeof t==='object'&&!Array.isArray(t)&&typeof t.id==='string'&&t.id.length>0&&t.id.length<=128&&typeof t.title==='string'&&t.title.trim().length>=1&&t.title.trim().length<=120&&typeof t.notes==='string'&&t.notes.length<=1000&&validDate(t.dueDate)&&['shared','private'].includes(t.scope)&&typeof t.assigneeUid==='string'&&t.assigneeUid.length<=128&&legacy.has(t.category)&&typeof t.ownerUid==='string'&&t.ownerUid.length>0&&typeof t.done==='boolean'&&Number.isSafeInteger(t.createdAt)&&t.createdAt>=0&&Number.isSafeInteger(t.updatedAt)&&t.updatedAt>=t.createdAt&&(t.sortOrder===undefined||(Number.isFinite(t.sortOrder)&&Math.abs(t.sortOrder)<=8e15));}
const note=(text,err=false)=>{$('message').textContent=text;$('message').hidden=!text;$('message').classList.toggle('error',err);};
const settingsError=text=>{$('settingsError').textContent=text;$('settingsError').hidden=!text;};
const haptic=()=>{if('vibrate' in navigator)try{navigator.vibrate(12);}catch(_){}};
function seed(){const names=['牛乳を買う','週末の予定を決める','資源ごみを出す'],now=Date.now();return names.map((title,i)=>({id:uuid(),title,notes:'',dueDate:'',category:'その他',assigneeUid:'',done:false,scope:'shared',ownerUid:'demo-me',createdAt:now,updatedAt:now,sortOrder:i*1024}));}
function loadDemo(){const raw=get(STORE);if(raw===null){const sample=seed();if(!set(STORE,JSON.stringify({version:1,tasks:sample})))note('端末内に保存できません。ブラウザの保存設定を確認してください。',true);return sample;}
try{const obj=JSON.parse(raw);if(obj.version!==1||!Array.isArray(obj.tasks)||obj.tasks.length>1000||!obj.tasks.every(validTask)||new Set(obj.tasks.map(t=>t.id)).size!==obj.tasks.length)throw Error();return obj.tasks;}
catch(_){state.blocked=true;note('旧データを読み込めません。上書きを防止しました。設定から正しいJSONを読み込んで復旧してください。',true);return [];}}
function saveDemo(next){if(state.blocked){note('保存データが破損しているため書き込みを停止しています。',true);return false;}if(!set(STORE,JSON.stringify({version:1,tasks:next}))){note('端末内に保存できませんでした。変更は反映していません。',true);return false;}state.tasks=next;render();return true;}
const collection=()=>{if(!state.family||!state.sdk)throw Error('先に家族スペースを作成してください。');return state.sdk.collection(state.connection.db,'families',state.family.id,'tasks');};
const ref=t=>state.sdk.doc(collection(),t.id);
const firebaseErr=e=>e?.code==='permission-denied'?'アクセス権がありません。Firebaseのルールと家族設定を確認してください。':e?.code==='auth/unauthorized-domain'?'認証ドメインにこのサイトを追加してください。':e?.code==='auth/popup-blocked'?'ポップアップを許可してください。':e?.message||'通信エラー';
async function persist(action,task,patch){if(state.busy)return false;
if(state.mode==='demo'){
const existing=state.tasks;let next;
if(action==='add')next=[...existing,task];else if(action==='delete')next=existing.filter(t=>t.id!==task.id);else next=existing.map(t=>t.id===task.id?{...t,...patch}:t);
return saveDemo(next);
}
if(!state.user||!state.family)throw Error('家族スペースへ接続してください。');
state.busy=true;try{if(action==='add'){const {id,...data}=task;await state.sdk.setDoc(ref(task),data);}else if(action==='delete')await state.sdk.deleteDoc(ref(task));else await state.sdk.updateDoc(ref(task),patch);return true;}
finally{state.busy=false;}}
function statusText(){if(state.mode==='demo')return '端末内デモ · ほかの端末とは同期しません';if(!state.user)return 'ログインして家族スペースに接続してください';if(!state.family)return '家族スペースを作成・参加してください';if(!navigator.onLine)return 'オフライン · 同期は接続回復後';if(state.metadata?.hasPendingWrites)return '同期中 · 反映待ち';if(state.metadata?.fromCache)return '保存済みデータを表示中 · 接続を確認しています';return 'Firebase共有リスト · 同期中';}
function render(){const shared=all(),rows=visible();$('count').textContent=`残り ${shared.filter(t=>!t.done).length} 件`;$('modeBadge').textContent=state.mode==='demo'?'端末内デモ':'家族共有';$('statusToggle').textContent=`${{open:'未完了',all:'すべて',done:'完了'}[state.status]} ↻`;$('syncStatus').textContent=statusText();$('empty').hidden=rows.length>0;const frag=document.createDocumentFragment();
rows.forEach((t,i)=>{const li=document.createElement('li');li.className='task'+(t.done?' done':'');li.dataset.taskId=t.id;li.tabIndex=0;li.setAttribute('aria-label',`${t.title}。右スワイプで完了、左スワイプで削除、長押しで並び替え。キーボードはAltと上下矢印で移動。`);
const colorIndex=Math.round(i*(colors.length-1)/Math.max(1,rows.length-1));const bg=t.done?'#d3d2cc':colors[colorIndex];li.style.background=bg;li.style.color=t.done||colorIndex>=3?'#35291d':'#fffdf6';
const reveal=document.createElement('div');reveal.className='action-reveal';reveal.innerHTML='<span>✓ 完了</span><span>削除 ×</span>';
const inner=document.createElement('div');inner.className='content';const check=document.createElement('button');check.type='button';check.className='check';check.textContent=t.done?'↶':'○';check.setAttribute('aria-label',`${t.title}を${t.done?'未完了':'完了'}にする`);check.disabled=state.blocked||state.mode==='firebase'&&(!state.user||!state.family);
check.addEventListener('click',async()=>{try{await toggle(t);}catch(e){note(`完了状態を保存できません：${firebaseErr(e)}`,true);}});
const body=document.createElement('button');body.type='button';body.className='body';const title=document.createElement('span');title.textContent=t.title;body.append(title);if(t.dueDate){const due=document.createElement('small');due.textContent=t.dueDate.slice(5).replace('-','/');body.append(due);}body.setAttribute('aria-label',`${t.title}を編集`);body.addEventListener('click',()=>edit(t));inner.append(check,body);li.append(reveal,inner);frag.append(li);});$('taskList').replaceChildren(frag);}
async function toggle(t){if(state.blocked)return;const ok=await persist('update',t,{done:!t.done,updatedAt:Math.max(Date.now(),t.createdAt)});if(ok){haptic();note(t.done?'未完了に戻しました。':'完了しました。');}}
async function remove(t){if(!window.confirm(`「${t.title}」を削除しますか？\nこの操作は元に戻せません。`))return false;try{const ok=await persist('delete',t);if(ok)note('削除しました。');return ok;}catch(e){note(`削除できません：${firebaseErr(e)}`,true);return false;}}
function openAdd(){if(state.blocked){note('破損した保存データを復旧してから追加してください。',true);return;}if(state.mode==='firebase'&&(!state.user||!state.family)){note('まず設定からログインして家族スペースを作成してください。',true);$('settingsDialog').showModal();return;}$('addForm').hidden=false;$('addFab').hidden=true;$('newTitle').focus();$('addForm').scrollIntoView({block:'nearest',behavior:'instant'});}
function closeAdd(){$('addForm').hidden=true;$('addFab').hidden=false;$('newTitle').value='';$('newDate').value='';$('newNotes').value='';$('newDetails').open=false;$('addError').hidden=true;}
function formValues(title,date,notes){const name=title.trim(),description=notes.trim();if(!name||name.length>120)throw Error('タスク名は1～120文字で入力してください。');if(description.length>1000)throw Error('メモは1000文字以内で入力してください。');if(!validDate(date))throw Error('期限の日付が正しくありません。');return {title:name,dueDate:date,notes:description};}
$('addForm').addEventListener('submit',async e=>{e.preventDefault();if(state.busy)return;$('addError').hidden=true;try{const v=formValues($('newTitle').value,$('newDate').value,$('newNotes').value),now=Date.now(),orders=all().map(rank),first=orders.length?Math.min(...orders)-1024:0;const task={id:uuid(),...v,category:'その他',assigneeUid:'',scope:'shared',ownerUid:uid(),done:false,createdAt:now,updatedAt:now,sortOrder:Number.isFinite(first)&&Math.abs(first)<8e15?first:0};if(!await persist('add',task))return;$('newTitle').value='';$('newDate').value='';$('newNotes').value='';$('newDetails').open=false;$('newTitle').focus();haptic();note('追加しました。続けて入力できます。');}catch(ex){$('addError').textContent=ex.message;$('addError').hidden=false;}});
$('addFab').addEventListener('click',openAdd);$('closeAdd').addEventListener('click',closeAdd);
$('statusToggle').addEventListener('click',()=>{state.status={open:'all',all:'done',done:'open'}[state.status];render();});
function edit(t){if(state.blocked||state.busy)return;state.editing=t;$('editTitle').value=t.title;$('editDate').value=t.dueDate;$('editNotes').value=t.notes;$('editError').hidden=true;$('editDialog').showModal();}
$('editClose').addEventListener('click',()=>$('editDialog').close());$('editDialog').addEventListener('close',()=>{state.editing=null;});
$('editForm').addEventListener('submit',async e=>{e.preventDefault();const t=state.editing;if(!t||state.busy)return;try{const values=formValues($('editTitle').value,$('editDate').value,$('editNotes').value),ok=await persist('update',t,{...values,updatedAt:Math.max(Date.now(),t.createdAt)});if(ok){$('editDialog').close();note('変更を保存しました。');}}catch(ex){$('editError').textContent=firebaseErr(ex);$('editError').hidden=false;}});
$('deleteEdit').addEventListener('click',async()=>{const t=state.editing;if(!t||state.busy)return;if(await remove(t))$('editDialog').close();});
function highlight(target){$('taskList').querySelectorAll('.drop-before,.drop-after').forEach(x=>x.classList.remove('drop-before','drop-after'));if(target)target.row.classList.add(target.after?'drop-after':'drop-before');}
function targetAt(x,y,id){const row=document.elementFromPoint(x,y)?.closest('li.task[data-task-id]');if(!row||!$('taskList').contains(row)||row.dataset.taskId===id)return null;return {row,id:row.dataset.taskId,after:y>row.getBoundingClientRect().top+row.getBoundingClientRect().height/2};}
function dragBegin(g){if(state.gesture!==g||state.busy)return;g.active=true;g.row.classList.add('dragging');$('dragGhost').textContent=g.row.querySelector('.body span')?.textContent||'';$('dragGhost').hidden=false;$('dragGhost').style.transform=`translate(${Math.max(8,g.x+14)}px,${Math.max(8,g.y-35)}px)`;window.getSelection()?.removeAllRanges();haptic();}
function cancelGesture(){const g=state.gesture;if(!g)return null;clearTimeout(g.timer);state.gesture=null;g.row.classList.remove('dragging','swiping','right');g.row.querySelector('.content').style.transform='';$('dragGhost').hidden=true;highlight(null);return g;}
async function reorder(from,to,after){if(state.busy||from===to)return false;const ordered=all().slice().sort(compare),beforeIds=ordered.map(t=>t.id).join('\0'),i=ordered.findIndex(t=>t.id===from),t=ordered.splice(i,1)[0],j=ordered.findIndex(x=>x.id===to);if(!t||j<0)throw Error('移動先が見つかりません。');ordered.splice(j+Number(after),0,t);if(beforeIds===ordered.map(x=>x.id).join('\0'))return false;const at=ordered.indexOf(t),lo=at>0?rank(ordered[at-1]):null,hi=at+1<ordered.length?rank(ordered[at+1]):null;const value=lo===null?(hi===null?0:hi-1024):hi===null?lo+1024:lo+(hi-lo)/2;const bad=!Number.isFinite(value)||Math.abs(value)>8e15||(lo!==null&&value<=lo)||(hi!==null&&value>=hi);const updates=bad?ordered.map((x,k)=>[x,k*1024]):[[t,value]],now=Date.now();if(state.mode==='demo'){const map=new Map(updates.map(([x,r])=>[x.id,r]));return saveDemo(state.tasks.map(x=>map.has(x.id)?{...x,sortOrder:map.get(x.id),updatedAt:Math.max(now,x.createdAt)}:x));}
if(updates.length>500)throw Error('タスク数が多すぎるため並び替えできません。');state.busy=true;try{if(updates.length===1){await state.sdk.updateDoc(ref(t),{sortOrder:value,updatedAt:Math.max(now,t.createdAt)});}else{const firestore=await import('https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js'),batch=firestore.writeBatch(state.connection.db);updates.forEach(([x,r])=>batch.update(ref(x),{sortOrder:r,updatedAt:Math.max(now,x.createdAt)}));await batch.commit();}return true;}finally{state.busy=false;}}
function arm(row,x,y,type,pointerId){if(state.gesture||state.busy||state.blocked||state.mode==='firebase'&&(!state.user||!state.family))return;const g={id:row.dataset.taskId,row,x,y,startX:x,startY:y,type,pointerId,axis:null,active:false,timer:null};g.timer=setTimeout(()=>dragBegin(g),type==='touch'?390:250);state.gesture=g;}
function gestureMove(x,y){const g=state.gesture;if(!g)return false;const dx=x-g.startX,dy=y-g.startY;g.x=x;g.y=y;if(g.active){$('dragGhost').style.transform=`translate(${Math.max(8,Math.min(x+14,innerWidth-232))}px,${Math.max(8,y-35)}px)`;highlight(targetAt(x,y,g.id));if(y<70)window.scrollBy(0,-15);else if(y>innerHeight-65)window.scrollBy(0,15);return true;}
if(!g.axis&&Math.hypot(dx,dy)>12){if(g.type==='touch'&&Math.abs(dx)>Math.abs(dy)*1.2){clearTimeout(g.timer);g.axis='horizontal';}else{cancelGesture();return false;}}
if(g.axis==='horizontal'){g.row.classList.add('swiping');g.row.classList.toggle('right',dx>0);g.row.querySelector('.content').style.transform=`translateX(${Math.max(-170,Math.min(170,dx))}px)`;return true;}return false;}
async function gestureEnd(x,y,canceled){const g=state.gesture;if(!g)return;g.x=x;g.y=y;const wasDrag=g.active,wasSwipe=g.axis==='horizontal',dx=x-g.startX,target=wasDrag&&!canceled?targetAt(x,y,g.id):null;cancelGesture();if(!wasDrag&&!wasSwipe)return;state.blockClickUntil=Date.now()+700;if(canceled)return;const t=all().find(x=>x.id===g.id);if(!t)return;
try{if(wasDrag&&target){if(await reorder(g.id,target.id,target.after))note('並び順を保存しました。');}else if(wasSwipe&&Math.abs(dx)>=76){if(dx>0)await toggle(t);else await remove(t);}}catch(ex){note(`操作を保存できません：${firebaseErr(ex)}`,true);}}
const list=$('taskList');let lastTouch=0;
list.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;lastTouch=Date.now();const row=e.target.closest('li.task');if(row)arm(row,e.touches[0].clientX,e.touches[0].clientY,'touch',null);},{passive:true});
list.addEventListener('touchmove',e=>{const g=state.gesture;if(!g||g.type!=='touch')return;if(e.touches.length!==1){cancelGesture();return;}if(gestureMove(e.touches[0].clientX,e.touches[0].clientY))e.preventDefault();},{passive:false});
list.addEventListener('touchend',e=>{const g=state.gesture;if(!g||g.type!=='touch')return;const p=e.changedTouches[0];if(g.active||g.axis==='horizontal')e.preventDefault();void gestureEnd(p?.clientX??g.x,p?.clientY??g.y,false);},{passive:false});
list.addEventListener('touchcancel',()=>{const g=state.gesture;if(g?.type==='touch')void gestureEnd(g.x,g.y,true);});
list.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||Date.now()-lastTouch<700||e.button!==0)return;const row=e.target.closest('li.task');if(row)arm(row,e.clientX,e.clientY,'mouse',e.pointerId);});
document.addEventListener('pointermove',e=>{if(state.gesture?.type==='mouse'&&state.gesture.pointerId===e.pointerId)gestureMove(e.clientX,e.clientY);});
document.addEventListener('pointerup',e=>{if(state.gesture?.type==='mouse'&&state.gesture.pointerId===e.pointerId)void gestureEnd(e.clientX,e.clientY,false);});
document.addEventListener('pointercancel',e=>{if(state.gesture?.type==='mouse'&&state.gesture.pointerId===e.pointerId)void gestureEnd(e.clientX,e.clientY,true);});
list.addEventListener('click',e=>{if(Date.now()<state.blockClickUntil){e.preventDefault();e.stopImmediatePropagation();}},true);
list.addEventListener('contextmenu',e=>e.preventDefault());list.addEventListener('selectstart',e=>e.preventDefault());list.addEventListener('dragstart',e=>e.preventDefault());
list.addEventListener('keydown',async e=>{if(!e.altKey||!['ArrowUp','ArrowDown'].includes(e.key)||e.target.closest('button,input'))return;const row=e.target.closest('li.task');if(!row)return;const rows=[...list.querySelectorAll('li.task')],i=rows.indexOf(row),down=e.key==='ArrowDown',other=rows[i+(down?1:-1)];if(!other)return;e.preventDefault();try{if(await reorder(row.dataset.taskId,other.dataset.taskId,down)){note('並び順を保存しました。');list.querySelectorAll('li.task')[i+(down?1:-1)]?.focus();}}catch(ex){note(`移動できません：${firebaseErr(ex)}`,true);}});
const wrap=$('listWrap');wrap.addEventListener('touchstart',e=>{if(e.touches.length!==1||!$('addForm').hidden||document.scrollingElement.scrollTop>8)return;const p=e.touches[0];state.pull={x:p.clientX,y:p.clientY,axis:null,dy:0};},{passive:true});
wrap.addEventListener('touchmove',e=>{const p=state.pull;if(!p||e.touches.length!==1)return;const t=e.touches[0],dx=t.clientX-p.x,dy=t.clientY-p.y;if(!p.axis&&Math.hypot(dx,dy)>13)p.axis=Math.abs(dy)>Math.abs(dx)*1.4?'vertical':'other';if(p.axis!=='vertical'||dy<=0){$('pull').style.height='0px';return;}if(state.gesture?.active){state.pull=null;$('pull').style.height='0px';return;}p.dy=Math.min(dy,140);$('pull').style.height=`${Math.min(72,dy*.65)}px`;$('pull').textContent=dy>90?'離して追加':'↓ 引いて追加';$('pull').classList.toggle('ready',dy>90);if(dy>20)e.preventDefault();},{passive:false});
wrap.addEventListener('touchend',()=>{const p=state.pull;state.pull=null;$('pull').style.height='0px';$('pull').classList.remove('ready');if(p?.axis==='vertical'&&p.dy>90)openAdd();});
wrap.addEventListener('touchcancel',()=>{state.pull=null;$('pull').style.height='0px';});
function configValid(c){return c&&typeof c==='object'&&['apiKey','authDomain','projectId','appId'].every(k=>typeof c[k]==='string'&&c[k].trim())&&!('private_key'in c)&&!('client_email'in c);}
function settingsRender(){const cloud=state.mode==='firebase';$('configInput').value=document.activeElement===$('configInput')?$('configInput').value:get(CONFIG)||'';$('accountSection').hidden=!cloud;$('accountInfo').textContent=state.user?`${state.user.displayName||'ログイン中'} · ${state.user.email||''}`:'ログインしていません';$('login').hidden=!!state.user;$('logout').hidden=!state.user;$('myUid').value=state.user?.uid||'';$('familyInfo').textContent=state.family?`家族スペース：${state.family.memberUids.length}/2人`:'家族スペースは未作成です';$('createFamily').hidden=!state.user||!!state.family;$('inviteBox').hidden=!state.family||state.family.ownerUid!==uid()||state.family.memberUids.length>=2;$('importFile').disabled=cloud;}
$('settingsOpen').addEventListener('click',()=>{settingsRender();settingsError('');$('settingsDialog').showModal();});$('settingsClose').addEventListener('click',()=>$('settingsDialog').close());
$('connect').addEventListener('click',()=>{try{const c=JSON.parse($('configInput').value.trim());if(!configValid(c))throw Error('firebaseConfigの必須項目が不足しています。');if(get(CONFIG)&&get(CONFIG)!==JSON.stringify(c)&&!confirm('同じサイト内のほかのアプリの接続設定にも影響します。変更しますか？'))return;if(!set(CONFIG,JSON.stringify(c))||!set(MODE,'firebase'))throw Error('設定を保存できません。');location.reload();}catch(e){settingsError(e.message);}});
$('disconnect').addEventListener('click',()=>{if(!confirm('この端末のFirebase接続設定を解除しますか？クラウド上のタスクは削除しません。同じサイト内のほかのアプリにも影響します。'))return;try{localStorage.removeItem(CONFIG);if(!set(MODE,'demo'))throw Error();location.reload();}catch(_){settingsError('設定を解除できませんでした。');}});
$('login').addEventListener('click',async()=>{try{await state.sdk.signInWithPopup(state.connection.auth,new state.sdk.GoogleAuthProvider());}catch(e){settingsError(firebaseErr(e));}});$('logout').addEventListener('click',async()=>{try{await state.sdk.signOut(state.connection.auth);}catch(e){settingsError(firebaseErr(e));}});
$('createFamily').addEventListener('click',async()=>{if(!state.user)return;try{await state.sdk.setDoc(state.sdk.doc(state.connection.db,'families',uid()),{ownerUid:uid(),memberUids:[uid()],createdAt:Date.now()});note('家族スペースを作成しました。');}catch(e){settingsError(firebaseErr(e));}});
$('invite').addEventListener('click',async()=>{const person=$('partnerUid').value.trim();if(!state.family||state.family.ownerUid!==uid()||person.length<12||person.length>128||person===uid()){settingsError('相手の正しいユーザーIDを入力してください。');return;}if(!confirm('入力したユーザーIDの相手に共有タスクが見えるようになります。IDを確認しましたか？'))return;try{await state.sdk.updateDoc(state.sdk.doc(state.connection.db,'families',state.family.id),{memberUids:[uid(),person]});note('共有相手を登録しました。');}catch(e){settingsError(firebaseErr(e));}});
function download(data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='family-tasks-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
$('export').addEventListener('click',()=>{if(state.blocked){settingsError('破損したデータは書き出せません。');return;}download({version:1,tasks:state.tasks});});
$('importFile').addEventListener('change',async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(state.mode!=='demo'){settingsError('FirebaseではJSONの読み込みはできません。');return;}if(file.size>2_000_000){settingsError('2MB以内のJSONファイルを選んでください。');return;}try{const obj=JSON.parse(await file.text());if(obj.version!==1||!Array.isArray(obj.tasks)||obj.tasks.length>1000||!obj.tasks.every(validTask)||new Set(obj.tasks.map(t=>t.id)).size!==obj.tasks.length)throw Error('対応していない、または破損したJSONです。');if(!confirm(`現在のデモタスクを${obj.tasks.length}件のバックアップで置き換えますか？旧個人タスクも含めて置換されます。`))return;if(!set(STORE,JSON.stringify(obj)))throw Error('保存できませんでした。');state.blocked=false;state.tasks=obj.tasks;render();settingsError('');note('JSONから復元しました。');}catch(ex){settingsError(`JSONを読み込めません：${ex.message}`);}});
function stopSubs(){state.taskUnsub?.();state.familyUnsub?.();state.taskUnsub=null;state.familyUnsub=null;state.family=null;state.tasks=[];state.metadata=null;}
function attachFamily(){state.familyUnsub=state.sdk.onSnapshot(state.sdk.query(state.sdk.collection(state.connection.db,'families'),state.sdk.where('memberUids','array-contains',uid())),snap=>{const doc=snap.docs[0],next=doc?{id:doc.id,...doc.data()}:null;const changed=(next?.id||'')!==(state.family?.id||'');state.family=next;if(changed){state.taskUnsub?.();state.taskUnsub=null;state.tasks=[];state.metadata=null;if(next)state.taskUnsub=state.sdk.onSnapshot(collection(),{includeMetadataChanges:true},tasks=>{state.tasks=tasks.docs.map(d=>({id:d.id,...d.data()}));state.metadata=tasks.metadata;render();},e=>note(`共有タスクを読み込めません：${firebaseErr(e)}`,true));}render();if($('settingsDialog').open)settingsRender();},e=>note(`家族情報を取得できません：${firebaseErr(e)}`,true));}
async function startFirebase(){try{const c=JSON.parse(get(CONFIG)||'null');if(!configValid(c))throw Error('Firebase設定の形式が正しくありません。');state.sdk=await import('../../assets/js/firebase-shared.js');state.connection=state.sdk.openSharedFirebase(c);state.authUnsub=state.sdk.onAuthStateChanged(state.connection.auth,user=>{stopSubs();state.user=user;if(user)attachFamily();render();if($('settingsDialog').open)settingsRender();},e=>note(firebaseErr(e),true));}catch(e){note(`Firebaseに接続できません：${firebaseErr(e)}。設定を確認してください。`,true);}}
window.addEventListener('online',render);window.addEventListener('offline',render);window.addEventListener('storage',e=>{if(state.mode==='demo'&&e.key===STORE){state.tasks=loadDemo();render();}});
state.mode=get(MODE)==='firebase'&&get(CONFIG)?'firebase':'demo';if(state.mode==='demo')state.tasks=loadDemo();render();if(state.mode==='firebase')void startFirebase();
})();