(() => {
  'use strict';
  const STORE = 'family-tasks:demo:v1';
  const MODE_KEY = 'family-tasks:mode:v1';
  const CONFIG_KEY = 'my-html-tools:firebase-config:v1';
  const SORT_MODE_KEY = 'family-tasks:sort-mode:v1';
  const CATEGORIES = ['家', '買い物', '子ども', 'その他'];
  const LEGACY_CATEGORIES = new Map([['家事', '家'], ['住宅', '家'], ['子育て', '子ども'], ['仕事', 'その他']]);
  const SORT_MODES = new Set(['manual', 'due', 'new']);
  const normalizeCategory = category => LEGACY_CATEGORIES.get(category) ?? category;
  const $ = id => document.getElementById(id);
  const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
  const plusDays = n => { const d = new Date(); d.setHours(12,0,0,0); d.setDate(d.getDate()+n); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
  const uuid = () => globalThis.crypto?.randomUUID?.() || `demo-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const getSaved = key => { try { return localStorage.getItem(key); } catch (_) { return null; } };
  const setSaved = (key,value) => { try { localStorage.setItem(key,value); return true; } catch (_) { return false; } };
  const validDate = value => {
    if(value==='') return true;
    if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
    const [y,m,d]=value.split('-').map(Number),date=new Date(y,m-1,d,12);
    return y>=1900&&y<=9999&&date.getFullYear()===y&&date.getMonth()+1===m&&date.getDate()===d;
  };
  let demoCorrupted=false;
  const validConfig=config=>config&&typeof config==='object'&&['apiKey','authDomain','projectId','appId'].every(k=>typeof config[k]==='string'&&config[k].trim())&&!('private_key' in config)&&!('client_email' in config);
  function normalizeTask(raw,allowDemo=false){
    if(!raw||typeof raw!=='object'||Array.isArray(raw)) throw Error('タスクの形式が正しくありません。');
    const title=typeof raw.title==='string'?raw.title.trim():'',notes=typeof raw.notes==='string'?raw.notes.trim():'',dueDate=raw.dueDate??'',category=normalizeCategory(raw.category);
    if(!title||title.length>120) throw Error('タスク名は1～120文字で入力してください。');
    if(notes.length>1000) throw Error('メモは1000文字以内で入力してください。');
    if(!validDate(dueDate)) throw Error('期限の日付が正しくありません。');
    if(!['shared','private'].includes(raw.scope)) throw Error('公開範囲が正しくありません。');
    if(typeof raw.assigneeUid!=='string'||raw.assigneeUid.length>128) throw Error('担当者が正しくありません。');
    if(typeof raw.done!=='boolean') throw Error('完了状態が正しくありません。');
    if(!CATEGORIES.includes(category)) throw Error('カテゴリが正しくありません。');
    if(raw.sortOrder!==undefined&&(!Number.isFinite(raw.sortOrder)||Math.abs(raw.sortOrder)>8e15)) throw Error('並び順の値が正しくありません。');
    if(!allowDemo&&(!raw.ownerUid||typeof raw.ownerUid!=='string')) throw Error('所有者が正しくありません。');
    const createdAt=Number.isSafeInteger(raw.createdAt)&&raw.createdAt>=0?raw.createdAt:Date.now(),updatedAt=Number.isSafeInteger(raw.updatedAt)&&raw.updatedAt>=0?raw.updatedAt:Date.now();
    return {title,notes,dueDate,scope:raw.scope,assigneeUid:raw.assigneeUid,category,done:raw.done,ownerUid:String(raw.ownerUid||'demo-me'),createdAt,updatedAt,...(raw.sortOrder===undefined?{}:{sortOrder:raw.sortOrder})};
  }
  const exampleTasks=()=>[
    {title:'ゴミ出しの準備',notes:'これはサンプルです。自由に編集・削除できます。',dueDate:today(),category:'家',scope:'shared',assigneeUid:'demo-me',done:false},
    {title:'牛乳を買う',notes:'',dueDate:plusDays(1),category:'買い物',scope:'shared',assigneeUid:'',done:false},
    {title:'書類を確認する',notes:'このタスクは自分だけに表示される想定です。',dueDate:'',category:'家',scope:'private',assigneeUid:'demo-me',done:false}
  ].map(t=>({id:uuid(),...normalizeTask({...t,ownerUid:'demo-me',createdAt:Date.now(),updatedAt:Date.now()},true)}));
  function showMessage(message){$('message').classList.remove('notice');$('message').textContent=message;$('message').hidden=!message;}
  function notify(message){showMessage(message);$('message').classList.add('notice');}
  function loadDemo(){
    const value=getSaved(STORE);
    if(value===null){const sample=exampleTasks();if(!setSaved(STORE,JSON.stringify({version:1,tasks:sample}))) showMessage('このブラウザでは端末内保存を利用できません。画面を閉じると変更が消えます。');return sample;}
    try{const parsed=JSON.parse(value);if(parsed.version!==1||!Array.isArray(parsed.tasks)||parsed.tasks.length>1000) throw Error();return parsed.tasks.map(t=>({id:typeof t.id==='string'&&t.id.length<=128?t.id:uuid(),...normalizeTask(t,true)}));}
    catch(_){demoCorrupted=true;showMessage('保存済みデータを読み込めません。元データを保護するため、書き込みを停止しています。正しいJSONを読み込んで復旧してください。');return [];}
  }
  const state={mode:getSaved(MODE_KEY)==='firebase'?'firebase':'demo',demo:[],privateTasks:[],sharedTasks:[],user:null,family:null,sdk:null,connection:null,unsubscribers:[],familyUnsub:null,sharedUnsub:null,privateUnsub:null,metadata:{private:null,shared:null},editing:null,creatingFamily:false,movingId:null,dateTargetId:null,drag:null,sortMode:SORT_MODES.has(getSaved(SORT_MODE_KEY))?getSaved(SORT_MODE_KEY):'due',reorderMode:false,oldFilters:null,sortDrag:null,sortBusy:false};
  state.demo=loadDemo();if(state.mode==='firebase'&&!getSaved(CONFIG_KEY)) state.mode='demo';
  const modeIsReady=()=>state.mode==='demo'?!demoCorrupted:!!state.user;
  const userId=()=>state.mode==='demo'?'demo-me':state.user?.uid||'';
  const partnerId=()=>state.mode==='demo'?'demo-partner':state.family?.memberUids.find(uid=>uid!==userId())||'';
  const allTasks=()=>state.mode==='demo'?state.demo:[...state.privateTasks,...state.sharedTasks];
  function taskCollection(scope){const {sdk,connection,family,user}=state;if(scope==='private') return sdk.collection(connection.db,'users',user.uid,'tasks');if(!family) throw Error('共有タスクには家族スペースの作成が必要です。');return sdk.collection(connection.db,'families',family.id,'tasks');}
  const docFor=task=>state.sdk.doc(taskCollection(task.scope),task.id);
  function saveDemo(){if(demoCorrupted){showMessage('破損した保存データの上書きを防ぐため、保存していません。正しいJSONを読み込んで復旧してください。');return false;}if(!setSaved(STORE,JSON.stringify({version:1,tasks:state.demo}))){showMessage('端末内保存に失敗しました。この画面を閉じると変更が失われます。');return false;}return true;}
  const taskToCloud=task=>{const {id:_id,...data}=task;return data;};
  function firebaseError(error){const code=error?.code||'';if(code==='permission-denied') return 'アクセス権がありません。Firestoreルールと家族登録を確認してください。';if(code==='auth/popup-blocked') return 'ポップアップがブロックされました。Safariの設定を確認してください。';if(code==='auth/popup-closed-by-user') return 'ログイン画面が閉じられました。';if(code==='auth/unauthorized-domain') return 'Firebase認証の承認済みドメインにこのサイトを追加してください。';return code?`エラーコード：${code}`:error?.message||'通信または保存のエラー';}
  function writeDoc(operation,task,update=null){const ref=docFor(task);let promise;if(operation==='add')promise=state.sdk.setDoc(ref,taskToCloud(task));if(operation==='update')promise=state.sdk.updateDoc(ref,update);if(operation==='delete')promise=state.sdk.deleteDoc(ref);promise.catch(e=>showMessage(`同期に失敗しました。データは確定していない可能性があります：${firebaseError(e)}`));setSyncStatus();}
  function setSyncStatus(extra=''){const node=$('syncStatus');node.classList.remove('pending','error');if(state.mode==='demo'){node.textContent='デモ · この端末にのみ保存（他端末には同期しません）';$('modeBadge').textContent='デモ';return;}$('modeBadge').textContent='Firebase';if(!state.user){node.textContent=extra||'Firebase接続 · ログイン待ち';return;}const meta=Object.values(state.metadata).filter(Boolean),pending=meta.some(m=>m.hasPendingWrites),cache=meta.some(m=>m.fromCache);if(!navigator.onLine||pending||cache){node.classList.add('pending');node.textContent=!navigator.onLine?'オフライン · 変更は端末に保持し、接続後に同期します':pending?'変更を同期中 · ほかの端末への反映は未完了':'キャッシュを表示中 · サーバーを確認しています';}else node.textContent=extra||'Firebaseと同期中 · 端末間で共有されます';}
  function adjustForm(){const ready=modeIsReady(),shareAvailable=state.mode==='demo'||!!state.family;$('taskTitle').disabled=!ready;$('taskDate').disabled=!ready;$('taskCategory').disabled=!ready;$('taskNotes').disabled=!ready;$('taskScope').disabled=!ready;$('taskScope').querySelector('[value="shared"]').disabled=!shareAvailable;if(!shareAvailable||!ready)$('taskScope').value='private';const personal=$('taskScope').value==='private';$('taskAssignee').disabled=!ready||personal;$('taskAssignee').querySelector('[value="partner"]').disabled=state.mode!=='demo'&&!partnerId();if(personal)$('taskAssignee').value='self';else if(!partnerId()&&$('taskAssignee').value==='partner')$('taskAssignee').value='';$('addBtn').disabled=!ready;$('reorderToggle').disabled=!ready||state.sortBusy;$('sortSelect').disabled=!ready||state.sortBusy;$('formHint').textContent=!ready?(demoCorrupted&&state.mode==='demo'?'破損したデータの復旧が必要です':'Firebaseにログインしてください'):!shareAvailable?'家族を作成すると共有タスクを追加できます':'公開範囲は作成後に変更できません';}
  function updateSettings(){if(document.activeElement!==$('configInput'))$('configInput').value=getSaved(CONFIG_KEY)||'';$('accountText').textContent=state.user?`${state.user.displayName||'ログイン中'} · ${state.user.email||''}`:state.sdk?'ログインしていません':'Firebase未接続';$('myUid').value=userId()==='demo-me'?'':userId();$('loginBtn').hidden=state.mode!=='firebase'||!state.sdk||!!state.user;$('logoutBtn').hidden=!state.user;$('demoBtn').hidden=state.mode==='demo';$('familySection').hidden=!state.user;$('createFamily').hidden=!!state.family;$('createFamily').disabled=state.creatingFamily;$('inviteArea').hidden=!state.family||state.family.ownerUid!==userId()||state.family.memberUids.length>=2;$('familyDescription').textContent=!state.family?'まだ家族スペースがありません。どちらか1人が作成してください。':`家族スペース：${state.family.memberUids.length}/2人 · ${state.family.ownerUid===userId()?'あなたが管理者':'相手が管理者'}`;$('importInput').disabled=state.mode!=='demo';$('exportBtn').disabled=demoCorrupted&&state.mode==='demo';$('importInput').previousElementSibling?.classList.toggle('disabled',state.mode!=='demo');adjustForm();}
  const assigneeName=uid=>uid===''?'担当なし・共同':uid===userId()?'担当：自分':'担当：相手';
  const manualRank=t=>Number.isFinite(t.sortOrder)?t.sortOrder:-t.createdAt;
  const compareManual=(a,b)=>manualRank(a)-manualRank(b)||a.id.localeCompare(b.id);
  function sortTasks(items){if(state.sortMode==='manual')return items.sort(compareManual);if(state.sortMode==='new')return items.sort((a,b)=>a.done-b.done||b.createdAt-a.createdAt||a.id.localeCompare(b.id));return items.sort((a,b)=>a.done-b.done||(a.dueDate||'9999-12-31').localeCompare(b.dueDate||'9999-12-31')||b.createdAt-a.createdAt||a.id.localeCompare(b.id));}
  const filterIds=['searchInput','scopeFilter','statusFilter','dateFilter'];
  function toggleReorder(forceOff=false){if(state.sortBusy||(!modeIsReady()&&!state.reorderMode))return;if(state.reorderMode||forceOff){if(!state.reorderMode)return;state.reorderMode=false;if(state.oldFilters)filterIds.forEach(id=>{$(id).value=state.oldFilters[id];});state.oldFilters=null;}else{hideMove();state.oldFilters=Object.fromEntries(filterIds.map(id=>[id,$(id).value]));$('searchInput').value='';$('scopeFilter').value='all';$('statusFilter').value='all';$('dateFilter').value='all';state.sortMode='manual';$('sortSelect').value='manual';if(!setSaved(SORT_MODE_KEY,'manual'))showMessage('並び順の表示設定を端末に保存できませんでした。');state.reorderMode=true;}render();}
  function moveTaskBeforeOrAfter(id,destinationId,after){
    if(!state.reorderMode||!modeIsReady()||state.sortBusy||id===destinationId)return false;
    const ordered=allTasks().slice().sort(compareManual),source=ordered.find(t=>t.id===id);
    if(!source)return false;
    const sourceIndex=ordered.indexOf(source);ordered.splice(sourceIndex,1);
    const targetIndex=ordered.findIndex(t=>t.id===destinationId);if(targetIndex<0)return false;
    ordered.splice(targetIndex+Number(after),0,source);if(ordered[sourceIndex]?.id===id)return false;
    const index=ordered.indexOf(source),before=ordered[index-1],following=ordered[index+1],low=before?manualRank(before):null,high=following?manualRank(following):null;
    const rank=low===null?(high===null?0:high-1024):high===null?low+1024:low+(high-low)/2;
    if(!Number.isFinite(rank)||Math.abs(rank)>8e15||(low!==null&&rank<=low)||(high!==null&&rank>=high)){
      const updates=ordered.map((task,i)=>({task,rank:i*1024}));
      if(state.mode==='demo'){const old=state.demo,ranks=new Map(updates.map(({task,rank})=>[task.id,rank]));state.demo=old.map(t=>ranks.has(t.id)?{...t,sortOrder:ranks.get(t.id)}:t);if(!saveDemo()){state.demo=old;render();return false;}render();notify('並び順を保存しました。');return true;}
      state.sortBusy=true;render();
      Promise.all(updates.map(({task,rank})=>state.sdk.updateDoc(docFor(task),{sortOrder:rank,updatedAt:Date.now()})))
        .then(()=>notify('共有の並び順を保存しました。')).catch(e=>showMessage(`並び順の同期に失敗しました：${firebaseError(e)}。Firestoreルールの更新を確認してください。`)).finally(()=>{state.sortBusy=false;render();});
      return true;
    }
    if(state.mode==='demo'){if(!updateTask(source,{sortOrder:rank,updatedAt:Date.now()}))return false;notify('並び順を端末に保存しました。');return true;}
    state.sortBusy=true;render();state.sdk.updateDoc(docFor(source),{sortOrder:rank,updatedAt:Date.now()}).then(()=>notify('共有の並び順を保存しました。')).catch(e=>showMessage(`並び順の同期に失敗しました：${firebaseError(e)}。Firestoreルールの更新を確認してください。`)).finally(()=>{state.sortBusy=false;render();});return true;
  }
  function shiftTask(id,direction){const ordered=allTasks().slice().sort(compareManual),index=ordered.findIndex(t=>t.id===id),neighbor=ordered[index+direction];if(index<0||!neighbor)return;moveTaskBeforeOrAfter(id,neighbor.id,direction>0);}
  function setupReorderHandle(handle,id){
    const clearVisuals=()=>{document.body.classList.remove('sorting-task','drag-arming');$('dragGhost').hidden=true;document.querySelectorAll('.sort-drop-before,.sort-drop-after').forEach(el=>el.classList.remove('sort-drop-before','sort-drop-after'));};
    let suppressClick=false;
    const targetAt=(x,y)=>{const target=document.elementFromPoint(x,y)?.closest('li.task[data-task-id]');if(!target||!$('taskList').contains(target)||target.dataset.taskId===id)return null;return {id:target.dataset.taskId,after:y>target.getBoundingClientRect().top+target.getBoundingClientRect().height/2,node:target};};
    const begin=drag=>{if(!state.reorderMode||state.sortBusy||state.sortDrag!==drag)return;drag.active=true;document.body.classList.add('sorting-task');$('dragGhost').textContent=allTasks().find(t=>t.id===id)?.title||'';$('dragGhost').hidden=false;};
    handle.addEventListener('pointerdown',event=>{if(event.button!==0||!state.reorderMode||state.sortBusy||state.sortDrag)return;const drag={id,pointerId:event.pointerId,x:event.clientX,y:event.clientY,active:false,timer:null};state.sortDrag=drag;document.body.classList.add('drag-arming');handle.setPointerCapture(event.pointerId);if(event.pointerType==='mouse'){begin(drag);event.preventDefault();}else drag.timer=setTimeout(()=>begin(drag),320);});
    handle.addEventListener('pointermove',event=>{const drag=state.sortDrag;if(!drag||drag.id!==id||drag.pointerId!==event.pointerId)return;if(!drag.active&&Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>12){clearTimeout(drag.timer);state.sortDrag=null;clearVisuals();if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);return;}if(!drag.active)return;event.preventDefault();$('dragGhost').style.transform=`translate(${Math.max(8,Math.min(event.clientX+14,innerWidth-170))}px, ${Math.max(8,event.clientY-40)}px)`;document.querySelectorAll('.sort-drop-before,.sort-drop-after').forEach(el=>el.classList.remove('sort-drop-before','sort-drop-after'));const target=targetAt(event.clientX,event.clientY);if(target)target.node.classList.add(target.after?'sort-drop-after':'sort-drop-before');});
    const end=(event,canceled)=>{const drag=state.sortDrag;if(!drag||drag.id!==id||drag.pointerId!==event.pointerId)return;clearTimeout(drag.timer);state.sortDrag=null;if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);const target=!canceled&&drag.active?targetAt(event.clientX,event.clientY):null;clearVisuals();if(drag.active){suppressClick=true;setTimeout(()=>{suppressClick=false;},0);if(target)moveTaskBeforeOrAfter(id,target.id,target.after);}};
    handle.addEventListener('pointerup',event=>end(event,false));handle.addEventListener('pointercancel',event=>end(event,true));handle.addEventListener('click',()=>{if(suppressClick){suppressClick=false;return;}notify('上下の矢印、またはハンドルの長押しドラッグで並び替えできます。');});
  }
  function render(){
    if(state.movingId&&!allTasks().some(t=>t.id===state.movingId))hideMove();
    const tasks=allTasks(),currentDate=today();
    $('todayCount').textContent=tasks.filter(t=>!t.done&&t.dueDate&&t.dueDate<=currentDate).length;
    $('upcomingCount').textContent=tasks.filter(t=>!t.done&&(!t.dueDate||t.dueDate>currentDate)).length;
    $('doneCount').textContent=tasks.filter(t=>t.done).length;
    const search=$('searchInput').value.trim().normalize('NFKC').toLowerCase(),scope=$('scopeFilter').value,status=$('statusFilter').value,dateFilter=$('dateFilter').value;
    const visible=tasks.filter(t=>{if(scope!=='all'&&t.scope!==scope)return false;if(status==='open'&&t.done||status==='done'&&!t.done)return false;if(search&&!`${t.title} ${t.notes} ${t.category}`.normalize('NFKC').toLowerCase().includes(search))return false;if(dateFilter==='today'&&(!t.dueDate||t.dueDate>currentDate))return false;if(dateFilter==='week'&&(!t.dueDate||t.dueDate>plusDays(7)))return false;if(dateFilter==='none'&&t.dueDate!=='')return false;return true;});
    sortTasks(visible);$('visibleCount').textContent=String(visible.length);$('sortSelect').value=state.sortMode;$('reorderToggle').textContent=state.reorderMode?'並び替えを終了':'並び替え';$('reorderToggle').setAttribute('aria-pressed',String(state.reorderMode));$('sortHint').textContent=state.reorderMode?'全タスクを表示中。↕を長押しして移動、または↑↓で1件ずつ移動できます。':'「≡」は担当・カテゴリ・期限の変更用です。';
    const fragment=document.createDocumentFragment();
    visible.forEach((task,position)=>{
      const item=document.createElement('li');item.className=`task${task.done?' done':''}`;item.dataset.taskId=task.id;
      const checkWrap=document.createElement('div');checkWrap.className='check-wrap';const check=document.createElement('input');check.type='checkbox';check.checked=task.done;check.setAttribute('aria-label',`${task.title}を${task.done?'未完了':'完了'}にする`);check.disabled=!modeIsReady();check.addEventListener('change',()=>updateTask(task,{done:check.checked,updatedAt:Date.now()}));checkWrap.append(check);
      const main=document.createElement('div');main.className='task-main';const title=document.createElement('p');title.className='task-title';title.textContent=task.title;main.append(title);const meta=document.createElement('div');meta.className='task-meta';const chip=(value,classname='')=>{const node=document.createElement('span');node.className=`chip ${classname}`;node.textContent=value;meta.append(node);};chip(task.scope==='private'?'自分だけ':'家族共有',task.scope);chip(task.category);chip(task.scope==='private'?'担当：自分':assigneeName(task.assigneeUid));if(task.dueDate)chip(task.dueDate<currentDate&&!task.done?`期限切れ ${task.dueDate}`:`期限 ${task.dueDate}`,task.dueDate<currentDate&&!task.done?'overdue':'');main.append(meta);if(task.notes){const notes=document.createElement('p');notes.className='task-notes';notes.textContent=task.notes;main.append(notes);}
      const edit=document.createElement('button');edit.type='button';edit.className='ghost edit-button';edit.textContent='編集';edit.disabled=!modeIsReady();edit.setAttribute('aria-label',`${task.title}を編集`);edit.addEventListener('click',()=>openEdit(task));
      const grip=document.createElement('button');grip.type='button';grip.className='drag-handle';grip.textContent=state.reorderMode?'↕':'≡';grip.disabled=!modeIsReady()||state.sortBusy;grip.dataset.taskId=task.id;
      if(state.reorderMode){grip.classList.add('sort-handle');grip.setAttribute('aria-label',`${task.title}をドラッグして並び替え`);setupReorderHandle(grip,task.id);const controls=document.createElement('div');controls.className='sort-arrows';const arrow=(text,direction,disabled)=>{const btn=document.createElement('button');btn.type='button';btn.className='ghost sort-arrow';btn.textContent=text;btn.setAttribute('aria-label',`${task.title}を${direction<0?'上':'下'}へ移動`);btn.disabled=disabled||state.sortBusy;btn.addEventListener('click',()=>shiftTask(task.id,direction));return btn;};controls.append(arrow('↑',-1,position===0),arrow('↓',1,position===visible.length-1));item.append(grip,checkWrap,main,controls,edit);}
      else{grip.setAttribute('aria-label',`${task.title}の担当・カテゴリ・期限を変更`);grip.setAttribute('aria-haspopup','true');setupDragHandle(grip,task.id);item.append(grip,checkWrap,main,edit);}fragment.append(item);
    });$('taskList').replaceChildren(fragment);$('emptyState').hidden=visible.length>0;$('emptyText').textContent=!modeIsReady()?'設定からGoogleでログインしてください。':tasks.length===0?'タスクはまだありません。右下の＋から追加できます。':'条件に合うタスクはありません。';updateSettings();setSyncStatus();
  }
  const selectedTask=()=>allTasks().find(t=>t.id===state.movingId)||null;
  function hideMove(){$('quickMove').hidden=true;$('dragGhost').hidden=true;document.body.classList.remove('moving-task');document.querySelectorAll('.move-target-hover').forEach(n=>n.classList.remove('move-target-hover'));state.movingId=null;}
  function showMove(id){const task=allTasks().find(t=>t.id===id);if(!task||!modeIsReady())return false;state.movingId=id;$('quickMoveTask').textContent=task.title;$('quickMove').hidden=false;const partner=$('quickMove').querySelector('[data-drop-kind="assignee"][data-drop-value="partner"]'),joint=$('quickMove').querySelector('[data-drop-kind="assignee"][data-drop-value=""]');partner.disabled=task.scope==='private'||!partnerId();joint.disabled=task.scope==='private';$('moveHelp').textContent=task.scope==='private'?'自分専用タスクは担当を他の人へ変更できません。カテゴリ・期限は変更できます。':!partnerId()?'相手を担当にするには家族の登録が必要です。':'移動先へドロップ、または項目をタップしてください。';return true;}
  function updateTask(task,patch){if(state.mode==='demo'){const index=state.demo.findIndex(t=>t.id===task.id);if(index<0)return false;const previous=state.demo[index];state.demo[index]={...previous,...patch};if(!saveDemo()){state.demo[index]=previous;render();return false;}render();return true;}if(state.user){writeDoc('update',task,patch);return true;}return false;}
  function applyMove(id,kind,value){const task=allTasks().find(t=>t.id===id);if(!task||!modeIsReady()){showMessage('タスクが見つからないか、ログインが必要です。');return false;}let patch,description;if(kind==='assignee'){if(!['self','partner',''].includes(value))return false;if(task.scope==='private'&&value!=='self'){showMessage('自分専用タスクは相手や共同の担当に変更できません。');return false;}if(value==='partner'&&!partnerId()){showMessage('先に家族の相手を登録してください。');return false;}const uid=value==='self'?userId():value==='partner'?partnerId():'';patch={assigneeUid:uid};description=value==='self'?'自分':value==='partner'?'相手':'共同';}else if(kind==='category'){if(!CATEGORIES.includes(value))return false;patch={category:value};description=value;}else if(kind==='date'){if(!validDate(value)){showMessage('期限の日付が正しくありません。');return false;}patch={dueDate:value};description=value||'期限なし';}else return false;try{const next=normalizeTask({...task,...patch,updatedAt:Date.now()},state.mode==='demo'),field=Object.keys(patch)[0];if(next[field]===task[field]){notify('変更はありません。');return true;}if(!updateTask(task,{[field]:next[field],updatedAt:next.updatedAt}))return false;notify(`${task.title} → ${description}（${state.mode==='demo'?'端末内に保存':'同期処理中'}）`);return true;}catch(e){showMessage(e.message);return false;}}
  function activateMove(kind,value){const id=state.movingId;if(!id)return;if(kind==='date'){if(value==='custom'){const task=selectedTask();if(!task)return;state.dateTargetId=id;$('moveDateInput').value=task.dueDate||today();$('moveDateTask').textContent=task.title;hideMove();$('moveDateDialog').showModal();$('moveDateInput').focus();return;}value=value==='today'?today():value==='tomorrow'?plusDays(1):value==='week'?plusDays(7):value==='none'?'':'__invalid__';}if(applyMove(id,kind,value))hideMove();}
  const dragTargetAt=(x,y)=>{const target=document.elementFromPoint(x,y)?.closest('[data-drop-kind]');return target&&$('quickMove').contains(target)&&!target.disabled?target:null;};
  function updateDragPosition(x,y){$('dragGhost').style.transform=`translate(${Math.min(x+14,innerWidth-170)}px, ${Math.max(8,y-40)}px)`;document.querySelectorAll('.move-target-hover').forEach(n=>n.classList.remove('move-target-hover'));const target=dragTargetAt(x,y);if(target)target.classList.add('move-target-hover');return target;}
  function setupDragHandle(handle,id){let ignoreClick=false;const begin=(x,y)=>{const drag=state.drag;if(!drag||drag.id!==id||drag.active||!showMove(id))return;drag.active=true;document.body.classList.add('moving-task');$('dragGhost').textContent=selectedTask()?.title||'';$('dragGhost').hidden=false;updateDragPosition(x,y);};handle.addEventListener('pointerdown',event=>{if(!modeIsReady()||event.button!==0||state.drag)return;const drag={id,pointerId:event.pointerId,active:false,timer:null,x:event.clientX,y:event.clientY};state.drag=drag;handle.setPointerCapture(event.pointerId);if(event.pointerType==='mouse'){begin(event.clientX,event.clientY);event.preventDefault();}else drag.timer=setTimeout(()=>begin(drag.x,drag.y),340);});handle.addEventListener('pointermove',event=>{const drag=state.drag;if(!drag||drag.id!==id||drag.pointerId!==event.pointerId)return;if(!drag.active&&Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>12){clearTimeout(drag.timer);state.drag=null;if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);return;}if(drag.active){updateDragPosition(event.clientX,event.clientY);event.preventDefault();}});const end=(event,canceled)=>{const drag=state.drag;if(!drag||drag.id!==id||drag.pointerId!==event.pointerId)return;clearTimeout(drag.timer);state.drag=null;if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);if(!drag.active)return;const target=!canceled&&dragTargetAt(event.clientX,event.clientY);$('dragGhost').hidden=true;document.body.classList.remove('moving-task');document.querySelectorAll('.move-target-hover').forEach(n=>n.classList.remove('move-target-hover'));ignoreClick=true;setTimeout(()=>{ignoreClick=false;},0);if(target)activateMove(target.dataset.dropKind,target.dataset.dropValue);else $('moveHelp').textContent='移動先をタップして変更するか、「閉じる」で中止できます。';};handle.addEventListener('pointerup',event=>end(event,false));handle.addEventListener('pointercancel',event=>end(event,true));handle.addEventListener('click',()=>{if(ignoreClick){ignoreClick=false;return;}if(state.movingId===id)hideMove();else{showMove(id);$('quickMove').querySelector('button[data-drop-kind]:not(:disabled)')?.focus();}});}
  $('quickMove').addEventListener('click',event=>{const button=event.target.closest('button[data-drop-kind]');if(button&&!button.disabled&&!state.drag?.active)activateMove(button.dataset.dropKind,button.dataset.dropValue);});
  $('cancelMove').addEventListener('click',hideMove);
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('quickMove').hidden&&!$('moveDateDialog').open)hideMove();});
  $('cancelMoveDate').addEventListener('click',()=>$('moveDateDialog').close());
  $('moveDateDialog').addEventListener('close',()=>{state.dateTargetId=null;});
  $('moveDateForm').addEventListener('submit',event=>{event.preventDefault();if(state.dateTargetId&&applyMove(state.dateTargetId,'date',$('moveDateInput').value))$('moveDateDialog').close();});
  function submitTask(values){const scope=values.scope;if(state.mode!=='demo'&&!state.user)throw Error('ログインしてください。');if(scope==='shared'&&state.mode!=='demo'&&!state.family)throw Error('家族スペースを先に作成してください。');const assigneeUid=scope==='private'?userId():values.assignee==='self'?userId():values.assignee==='partner'?partnerId():'';if(values.assignee==='partner'&&!assigneeUid)throw Error('相手の登録が完了していません。');if(!['',userId(),partnerId()].includes(assigneeUid))throw Error('担当者が正しくありません。');return normalizeTask({title:values.title,notes:values.notes,dueDate:values.dueDate,scope,category:values.category,assigneeUid,ownerUid:userId(),done:false,createdAt:Date.now(),updatedAt:Date.now()});}
  function openEdit(task){if(!modeIsReady())return;state.editing=task;$('editScopeInfo').textContent=`${task.scope==='shared'?'家族共有':'自分だけ'} · 公開範囲は変更できません`;$('editTaskTitle').value=task.title;$('editTaskDate').value=task.dueDate;$('editTaskCategory').value=task.category;$('editTaskNotes').value=task.notes;$('editTaskAssignee').disabled=task.scope==='private';$('editTaskAssignee').querySelector('[value="partner"]').disabled=state.mode!=='demo'&&!partnerId();$('editTaskAssignee').value=task.scope==='private'?'self':task.assigneeUid===''?'':task.assigneeUid===userId()?'self':'partner';$('editDialog').showModal();}
  function closeEdit(){$('editDialog').close();state.editing=null;}
  async function startFirebase(){const configText=getSaved(CONFIG_KEY);if(!configText)throw Error('Firebase設定がありません。');const config=JSON.parse(configText);if(!validConfig(config))throw Error('Firebase設定の必須項目が不足しています。');state.sdk=await import('../../assets/js/firebase-shared.js');state.connection=state.sdk.openSharedFirebase(config);state.unsubscribers.push(state.sdk.onAuthStateChanged(state.connection.auth,user=>{clearSubscriptions();state.user=user;state.family=null;state.privateTasks=[];state.sharedTasks=[];state.metadata={private:null,shared:null};if(user)attachUser(user.uid);render();},error=>showMessage(`認証状態の取得に失敗しました：${firebaseError(error)}`)));render();}
  function clearSubscriptions(){if(state.familyUnsub){state.familyUnsub();state.familyUnsub=null;}if(state.sharedUnsub){state.sharedUnsub();state.sharedUnsub=null;}if(state.privateUnsub){state.privateUnsub();state.privateUnsub=null;}}
  function attachUser(uid){const {sdk,connection}=state;state.privateUnsub=sdk.onSnapshot(sdk.collection(connection.db,'users',uid,'tasks'),{includeMetadataChanges:true},snapshot=>{state.privateTasks=snapshot.docs.map(item=>({id:item.id,...item.data(),category:normalizeCategory(item.data().category)}));state.metadata.private=snapshot.metadata;render();},error=>showMessage(`個人タスクの読込に失敗しました：${firebaseError(error)}`));const families=sdk.query(sdk.collection(connection.db,'families'),sdk.where('memberUids','array-contains',uid));state.familyUnsub=sdk.onSnapshot(families,{includeMetadataChanges:true},snapshot=>{const familyDoc=snapshot.docs[0]||null,nextFamily=familyDoc?{id:familyDoc.id,...familyDoc.data()}:null,oldId=state.family?.id||'';state.family=nextFamily;if((nextFamily?.id||'')!==oldId){if(state.sharedUnsub){state.sharedUnsub();state.sharedUnsub=null;}state.sharedTasks=[];state.metadata.shared=null;if(nextFamily)attachShared(nextFamily.id);}render();},error=>showMessage(`家族情報の読込に失敗しました：${firebaseError(error)}`));}
  function attachShared(familyId){const {sdk,connection}=state;state.sharedUnsub=sdk.onSnapshot(sdk.collection(connection.db,'families',familyId,'tasks'),{includeMetadataChanges:true},snapshot=>{state.sharedTasks=snapshot.docs.map(item=>({id:item.id,...item.data(),category:normalizeCategory(item.data().category)}));state.metadata.shared=snapshot.metadata;render();},error=>showMessage(`共有タスクの読込に失敗しました：${firebaseError(error)}`));}
  function showSettings(open){$('settings').hidden=!open;$('settingsToggle').setAttribute('aria-expanded',String(open));if(open){updateSettings();$('settings').scrollIntoView({block:'nearest'});}}
  $('settingsToggle').addEventListener('click',()=>showSettings($('settings').hidden));$('closeSettings').addEventListener('click',()=>showSettings(false));$('taskScope').addEventListener('change',adjustForm);
  $('sortSelect').addEventListener('change',event=>{const next=event.target.value;if(!SORT_MODES.has(next)||state.sortBusy)return;if(state.reorderMode)toggleReorder(true);state.sortMode=next;if(!setSaved(SORT_MODE_KEY,next))showMessage('並び順の表示設定を端末に保存できませんでした。');render();});
  $('reorderToggle').addEventListener('click',()=>toggleReorder());$('taskList').addEventListener('selectstart',event=>event.preventDefault());$('taskList').addEventListener('dragstart',event=>event.preventDefault());
  ['searchInput','scopeFilter','statusFilter','dateFilter'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',render));
  $('addForm').addEventListener('submit',event=>{event.preventDefault();try{const task={id:uuid(),...submitTask({title:$('taskTitle').value,notes:$('taskNotes').value,dueDate:$('taskDate').value,scope:$('taskScope').value,assignee:$('taskAssignee').value,category:$('taskCategory').value})};let saved=true;if(state.mode==='demo'){state.demo.push(task);saved=saveDemo();render();}else writeDoc('add',task);if(saved){$('taskTitle').value='';$('taskNotes').value='';$('taskTitle').focus();notify(state.mode==='demo'?'タスクを端末内に追加しました。':'タスクを送信しました。同期完了は上部の表示で確認してください。');}}catch(e){showMessage(e.message);}});
  $('cancelEdit').addEventListener('click',closeEdit);$('editDialog').addEventListener('close',()=>{state.editing=null;});
  $('editForm').addEventListener('submit',event=>{event.preventDefault();const task=state.editing;if(!task)return;try{const title=$('editTaskTitle').value.trim(),notes=$('editTaskNotes').value.trim(),dueDate=$('editTaskDate').value,category=$('editTaskCategory').value,assignee=$('editTaskAssignee').value,assigneeUid=task.scope==='private'?userId():assignee===''?'':assignee==='self'?userId():partnerId();if(assignee==='partner'&&!partnerId())throw Error('相手の登録が完了していません。');const next=normalizeTask({...task,title,notes,dueDate,category,assigneeUid,updatedAt:Date.now()});updateTask(task,{title:next.title,notes:next.notes,dueDate:next.dueDate,category:next.category,assigneeUid:next.assigneeUid,updatedAt:next.updatedAt});closeEdit();notify(state.mode==='demo'?'変更を反映しました。':'変更を送信しました。同期完了は上部の表示で確認してください。');}catch(e){showMessage(e.message);}});
  $('deleteTask').addEventListener('click',()=>{const task=state.editing;if(!task||!window.confirm(`「${task.title}」を削除しますか？`))return;if(state.mode==='demo'){state.demo=state.demo.filter(t=>t.id!==task.id);saveDemo();render();}else writeDoc('delete',task);closeEdit();notify(state.mode==='demo'?'削除しました。':'削除を送信しました。同期完了は上部の表示で確認してください。');});
  $('saveConfig').addEventListener('click',()=>{try{const config=JSON.parse($('configInput').value.trim());if(!validConfig(config))throw Error('firebaseConfigのapiKey・authDomain・projectId・appIdが必要です。');const old=getSaved(CONFIG_KEY);if(old&&old!==JSON.stringify(config)&&!window.confirm('共通Firebase設定を変更します。ほかのアプリにも影響する可能性があります。続行しますか？'))return;if(!setSaved(CONFIG_KEY,JSON.stringify(config))||!setSaved(MODE_KEY,'firebase'))throw Error('設定を保存できません。ブラウザの保存許可を確認してください。');location.reload();}catch(e){showMessage(`設定できません：${e.message}`);}});
  $('removeConfig').addEventListener('click',()=>{if(!window.confirm('同じサイト内のほかのアプリも使う共通Firebase設定を削除しますか？クラウドのタスク自体は削除されません。'))return;try{localStorage.removeItem(CONFIG_KEY);localStorage.setItem(MODE_KEY,'demo');location.reload();}catch(_){showMessage('設定を削除できませんでした。');}});
  $('demoBtn').addEventListener('click',()=>{setSaved(MODE_KEY,'demo');location.reload();});
  $('loginBtn').addEventListener('click',()=>{if(!state.connection)return;state.sdk.signInWithPopup(state.connection.auth,new state.sdk.GoogleAuthProvider()).catch(e=>showMessage(`ログインできません：${firebaseError(e)}`));});
  $('logoutBtn').addEventListener('click',()=>{if(state.connection)state.sdk.signOut(state.connection.auth).catch(e=>showMessage(`ログアウトできません：${firebaseError(e)}`));});
  $('copyUid').addEventListener('click',async()=>{if(!state.user){showMessage('ログイン後にコピーできます。');return;}try{await navigator.clipboard.writeText(state.user.uid);notify('ユーザーIDをコピーしました。');}catch(_){$('myUid').focus();$('myUid').select();showMessage('コピーできません。選択されたIDを手動でコピーしてください。');}});
  $('createFamily').addEventListener('click',()=>{if(!state.user||state.family||state.creatingFamily)return;state.creatingFamily=true;updateSettings();const {sdk,connection,user}=state,ref=sdk.doc(connection.db,'families',user.uid);sdk.setDoc(ref,{ownerUid:user.uid,memberUids:[user.uid],createdAt:Date.now()}).catch(e=>showMessage(`家族の作成に失敗しました：${firebaseError(e)}`)).finally(()=>{state.creatingFamily=false;updateSettings();});notify('家族スペースの作成を送信しました。同期完了後に共有タスクを追加できます。');});
  $('addPartner').addEventListener('click',()=>{const targetUid=$('partnerUid').value.trim();if(!state.family||state.family.ownerUid!==userId()){showMessage('家族の管理者のみ変更できます。');return;}if(!/^[A-Za-z0-9:_-]{6,128}$/.test(targetUid)||targetUid===userId()){showMessage('相手の正しいユーザーIDを入力してください。');return;}if(state.family.memberUids.length>=2){showMessage('プロトタイプは2人までです。');return;}if(!window.confirm('IDが正しいことを確認しましたか？登録したIDの利用者は家族共有タスクを閲覧できます。'))return;const ref=state.sdk.doc(state.connection.db,'families',state.family.id);state.sdk.updateDoc(ref,{memberUids:[state.family.ownerUid,targetUid]}).catch(e=>showMessage(`共有設定に失敗しました：${firebaseError(e)}`));notify('共有設定を送信しました。相手がログインすると共有タスクが表示されます。');});
  $('exportBtn').addEventListener('click',()=>{try{if(demoCorrupted&&state.mode==='demo')throw Error('破損データを保護中のためエクスポートできません。');const payload={version:1,exportedAt:new Date().toISOString(),mode:state.mode,tasks:allTasks()},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`family-tasks-${today()}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);notify(state.mode==='firebase'?'現在表示できているデータを保存しました。キャッシュ中は一部が未取得の可能性があります。':'JSONバックアップを書き出しました。');}catch(_){showMessage('JSONの保存に失敗しました。');}});
  $('importInput').addEventListener('change',async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(state.mode!=='demo'){showMessage('Firebaseモードではインポートを受け付けません。');return;}if(file.size>2_000_000){showMessage('JSONファイルは2MB以内にしてください。');return;}try{const payload=JSON.parse(await file.text());if(payload.version!==1||!Array.isArray(payload.tasks)||payload.tasks.length>1000)throw Error('対応していないJSON形式です。');const imported=payload.tasks.map(item=>({id:uuid(),...normalizeTask(item,true)}));if(!window.confirm(`現在のデモタスク${state.demo.length}件を、読み込んだ${imported.length}件で置き換えますか？`))return;demoCorrupted=false;state.demo=imported;saveDemo();render();notify(`${imported.length}件を読み込みました。`);}catch(e){showMessage(`JSONを読み込めません：${e.message}`);}});
  window.addEventListener('online',()=>setSyncStatus());window.addEventListener('offline',()=>setSyncStatus());window.addEventListener('storage',event=>{if(state.mode==='demo'&&event.key===STORE){state.demo=loadDemo();render();}});
  render();if(state.mode==='firebase'){setSyncStatus('Firebase SDKを読み込み中');startFirebase().catch(e=>{showMessage(`Firebaseに接続できません：${firebaseError(e)}。設定を確認するか「デモに戻る」を選んでください。`);$('syncStatus').textContent='Firebase接続エラー · デモモードへの切り替えは設定から';$('syncStatus').classList.add('error');updateSettings();});}
})();