(() => {
'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),stage=$('stage'),panel=$('panel'),overlay=$('overlay');
const hud=$('hud'),dropBtn=$('drop'),scoreLabel=$('scoreLabel'),timeLabel=$('timeLabel'),modeLabel=$('modeLabel'),swingLabel=$('swingLabel'),windLabel=$('windLabel'),countLabel=$('countLabel'),sensorLabel=$('sensorLabel'),message=$('message');
const STORE='gyro-crane:v1',modes={rush:{name:'90秒チャレンジ',desc:'90秒で何個運べる？',limit:90},precision:{name:'精密着地',desc:'5回の着地精度を競う',limit:0},tower:{name:'崩壊タワー',desc:'8段積めたらクリア',limit:0},wind:{name:'強風モード',desc:'風を読んで90秒運ぶ',limit:90}};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rand=(a,b)=>a+Math.random()*(b-a);
let saved={};try{saved=JSON.parse(localStorage.getItem(STORE))||{}}catch(_){};
let mode='rush',sound=saved.sound!==false,world={w:360,h:510},state='menu',game=null,lastFrame=0,accumulator=0,noticeUntil=0,noticeText='';
let filteredInput=0,leftDown=false,rightDown=false,audio=null;
function save(){try{localStorage.setItem(STORE,JSON.stringify(saved))}catch(_){}}
function audioReady(){if(!sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{})}catch(_){}}
function tone(f,d=.1){if(!sound||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.78,audio.currentTime+d);g.gain.setValueAtTime(.075,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(_){}}
function vibrate(ms){if(navigator.vibrate)navigator.vibrate(ms)}
function resize(){const r=stage.getBoundingClientRect();if(!r.width||!r.height)return;const dpr=Math.min(devicePixelRatio||1,2);world.h=360*r.height/r.width;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(canvas.width/360,0,0,canvas.height/world.h,0,0);if(game){game.platformY=world.h-59-game.stack*21;game.rope=clamp(world.h*.27,84,144)}}
window.addEventListener('resize',()=>{resize();if(state==='playing'&&matchMedia('(orientation:landscape) and (max-height:430px)').matches)pause()});resize();
function showNotice(t,seconds=1.1){noticeText=t;noticeUntil=performance.now()+seconds*1000;message.textContent=t;message.classList.add('show')}
function safeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function startMenu(){state='menu';overlay.hidden=false;hud.hidden=true;dropBtn.disabled=true;panel.innerHTML=`<div class="kicker">MOVE · SWING · DROP</div><h1>ぐらぐら<br>クレーン！</h1><p class="sub">左右ボタンでクレーンを動かそう。<br>荷物は振り子のように揺れる。<strong>逆方向に動かして揺れを止めよう！</strong></p><div class="modes">${Object.entries(modes).map(([id,m])=>`<button class="mode" type="button" data-mode="${id}" aria-pressed="${id===mode}">${m.name}<small>${m.desc}</small></button>`).join('')}</div><div class="rules"><b>◀ / ▶</b>　押している間クレーンを左右に移動<br><b>DROP</b>　着地点の中心を狙って荷物を落とす<br><b>コツ</b>　早めに逆方向へ動かして振れ止め！<br><b>PC</b>　← → キーで移動、スペースで落下</div><label class="setting">効果音 <input id="sound" type="checkbox" ${sound?'checked':''}></label><button class="primary" type="button" data-action="start">荷役スタート！</button><p class="note">画面を傾ける必要はありません。固定画面で荷物の揺れを見ながら操作できます。記録は端末内保存です。</p>`;}
const cargoTypes=[{id:'box',name:'コンテナ',w:48,h:34,color:'#e99e42'},{id:'pipe',name:'長い鉄パイプ',w:76,h:18,color:'#8fc4d3'},{id:'water',name:'水槽',w:50,h:39,color:'#4fc8ce'},{id:'fragile',name:'精密機械',w:46,h:37,color:'#b58ef1'}];
function nextCargo(){if(!game)return;game.phase='carry';game.trolleyX=clamp(game.targetX+rand(-120,120),46,314);if(Math.abs(game.trolleyX-game.targetX)<85)game.trolleyX=game.targetX<180?300:60;game.vx=0;game.ax=0;game.theta=rand(-.045,.045);game.omega=0;game.dropObj=null;game.cargo=mode==='tower'?{...cargoTypes[0],w:56,h:21}:cargoTypes[(game.attempts+Math.floor(rand(0,3)))%cargoTypes.length];if(mode!=='tower'){const p=game.cargo.id==='pipe'?90:mode==='precision'?66:82;game.targetWidth=p;game.targetX=rand(65,295)}game.platformY=world.h-59-game.stack*21;dropBtn.disabled=false;}
function newGame(){const best=saved.best?.[mode]||0;game={elapsed:0,time:modes[mode].limit,score:0,best,attempts:0,success:0,misses:0,combo:0,stack:0,targetX:180,targetWidth:82,platformY:world.h-59,rope:clamp(world.h*.27,84,144),trolleyX:82,vx:0,ax:0,theta:0,omega:0,phase:'carry',dropObj:null,cargo:cargoTypes[0],wind:0,lastGrade:'',complete:false};if(mode==='tower'){game.targetX=180;game.targetWidth=73;}nextCargo();state='playing';overlay.hidden=true;hud.hidden=false;lastFrame=0;accumulator=0;filteredInput=0;leftDown=rightDown=false;refreshButtons();updateHUD();}
function getInput(){return Number(rightDown)-Number(leftDown)}
function cargoPoint(){const g=game;return{x:g.trolleyX+g.rope*Math.sin(g.theta),y:75+g.rope*Math.cos(g.theta),vx:g.vx+g.rope*Math.cos(g.theta)*g.omega,vy:-g.rope*Math.sin(g.theta)*g.omega}}
function landingX(){const p=cargoPoint(),g=game,dy=g.platformY-g.cargo.h/2-p.y,disc=p.vy*p.vy+2*1100*dy;if(disc<0)return p.x;const t=Math.max(0,(-p.vy+Math.sqrt(disc))/1100);return p.x+p.vx*t;}
function drop(){if(state!=='playing'||game.phase!=='carry')return;const p=cargoPoint();game.dropObj={x:p.x,y:p.y,vx:p.vx,vy:p.vy,angle:game.theta,spin:game.omega,w:game.cargo.w,h:game.cargo.h};game.phase='fall';dropBtn.disabled=true;tone(460,.09)}
function refreshButtons(){$('left').classList.toggle('pressed',leftDown);$('right').classList.toggle('pressed',rightDown)}
function clearHeld(){leftDown=false;rightDown=false;refreshButtons()}
for(const [id,side] of [['left','left'],['right','right']]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();try{b.setPointerCapture(e.pointerId)}catch(_){/* synthetic pointers or unsupported capture */}if(side==='left')leftDown=true;else rightDown=true;refreshButtons()});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{if(side==='left')leftDown=false;else rightDown=false;refreshButtons()});}
dropBtn.addEventListener('click',drop);$('pauseBtn').addEventListener('click',pause);
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','Enter'].includes(e.key)&&!['INPUT','BUTTON'].includes(document.activeElement.tagName))e.preventDefault();if(e.key==='ArrowLeft')leftDown=true;if(e.key==='ArrowRight')rightDown=true;if((e.key===' '||e.key==='Enter')&&state==='playing')drop();if(e.key==='Escape'&&state==='playing')pause();refreshButtons()});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft')leftDown=false;if(e.key==='ArrowRight')rightDown=false;refreshButtons()});window.addEventListener('blur',()=>{clearHeld();if(state==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
function pause(){if(state!=='playing')return;state='paused';clearHeld();overlay.hidden=false;dropBtn.disabled=true;panel.innerHTML='<div class="kicker">BREAK TIME</div><h2>一時停止</h2><p class="sub">左右ボタンで振れを止め、DROPで着地させよう。</p><button class="primary" data-action="resume" type="button">再開する</button><button class="secondary" data-action="menu" type="button">モード選択へ戻る</button>';}
function resume(){if(state!=='paused')return;filteredInput=0;state='playing';overlay.hidden=true;dropBtn.disabled=game.phase!=='carry';lastFrame=0;}
function finish(reason){if(state!=='playing')return;state='result';clearHeld();dropBtn.disabled=true;hud.hidden=false;overlay.hidden=false;const recordValue=mode==='tower'?game.stack:game.score;const best=Math.max(Number(saved.best?.[mode])||0,recordValue);const record=recordValue>Number(saved.best?.[mode]||0);saved.best={...(saved.best||{}),[mode]:best};saved.plays=(saved.plays||0)+1;save();const heading=reason==='time'?'作業終了！':reason==='collapse'?'タワー崩壊！':reason==='clear'?'MISSION CLEAR!':'作業結果';panel.innerHTML=`<div class="kicker">${safeHTML(modes[mode].name)}</div><h2>${heading}</h2><div class="score">${mode==='tower'?game.stack+'段':game.score.toLocaleString()+' pt'}</div><div class="sub">${record?'NEW RECORD!　':''}${safeHTML(reason==='collapse'?'積み上げに失敗。再挑戦で記録更新！':reason==='clear'?'目標を達成しました！':'振れ止め技術を磨いて自己記録を狙おう。')}</div><div class="results"><div>成功<b>${game.success} 個</b></div><div>失敗<b>${game.misses} 回</b></div><div>最高連続成功<b>${game.bestCombo||0} 回</b></div><div>自己ベスト<b>${best.toLocaleString()}${mode==='tower'?' 段':' pt'}</b></div></div><button class="primary" data-action="retry" type="button">もう一度遊ぶ</button><button class="secondary" data-action="menu" type="button">モードを変更</button>`;tone(reason==='clear'?820:330,.23)}
panel.addEventListener('click',e=>{const modeBtn=e.target.closest('[data-mode]');if(modeBtn){mode=modeBtn.dataset.mode;panel.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===modeBtn)));return}const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='start'){audioReady();newGame();}else if(action==='resume')resume();else if(action==='retry'){audioReady();newGame()}else if(action==='menu')startMenu()});
panel.addEventListener('input',e=>{if(e.target.id==='sound'){sound=e.target.checked;saved.sound=sound;save();if(sound)audioReady()}});
function updateHUD(){if(!game)return;modeLabel.textContent=modes[mode].name;timeLabel.textContent=game.time>0?`残り ${Math.ceil(game.time)}秒`:mode==='tower'?`${game.stack}/8 段`:`${game.attempts}/5 回`;scoreLabel.textContent=game.score.toLocaleString();countLabel.textContent=`成功 ${game.success} / 失敗 ${game.misses}`;swingLabel.textContent=`揺れ ${Math.abs(game.theta*180/Math.PI).toFixed(1)}°`;windLabel.textContent=mode==='wind'?`風 ${game.wind>=0?'→':'←'} ${Math.abs(Math.round(game.wind))}`:'風 なし'}
function evaluate(){const g=game,o=g.dropObj,dx=o.x-g.targetX,speed=Math.abs(o.vx),isTower=mode==='tower';const tolerance=isTower?Math.max(9,24-g.stack*1.3):Math.max(10,(g.targetWidth-g.cargo.w)/2+8);let ok=Math.abs(dx)<=tolerance&&speed<185;if(g.cargo.id==='fragile'&&speed>95)ok=false;if(g.cargo.id==='water'&&speed>130)ok=false;g.attempts++;if(ok){g.success++;g.combo++;g.bestCombo=Math.max(g.bestCombo||0,g.combo);const precision=clamp(1-Math.abs(dx)/Math.max(tolerance,1),0,1);const quality=Math.max(0,Math.round(precision*100-speed*.13));const perfect=Math.abs(dx)<7&&speed<35;const points=(perfect?500:Math.round(110+quality*3))*(1+Math.min(4,g.combo-1));g.score+=points;g.lastGrade=perfect?'PERFECT!':quality>=65?'GREAT!':'DELIVERED!';showNotice(`${g.lastGrade} +${points}`,1);tone(perfect?1050:740,.16);if(perfect)vibrate(35);if(isTower){g.stack++;if(g.stack>=8){finish('clear');return}}}else{g.misses++;g.combo=0;g.lastGrade=isTower?'COLLAPSE!':'MISS!';showNotice(g.lastGrade,1);tone(190,.25);vibrate(90);if(isTower){finish('collapse');return}}g.phase='wait';g.wait=1.15;if(mode==='precision'&&g.attempts>=5){g.wait=.8;g.complete=true}}
function step(dt){if(!game||state!=='playing')return;const g=game;g.elapsed+=dt;if(modes[mode].limit){g.time=Math.max(0,modes[mode].limit-g.elapsed);if(g.time<=0){finish('time');return}}g.wind=mode==='wind'?Math.sin(g.elapsed*1.6)*95+Math.sin(g.elapsed*.61)*38:0;if(g.phase==='carry'){const input=getInput();filteredInput+=(input-filteredInput)*Math.min(1,dt*12);const desired=filteredInput*235;g.ax=clamp((desired-g.vx)*5.5,-690,690);g.vx+=g.ax*dt;g.trolleyX+=g.vx*dt;if(g.trolleyX<37){g.trolleyX=37;g.vx=0;g.ax=0}if(g.trolleyX>323){g.trolleyX=323;g.vx=0;g.ax=0}const grav=1280,angleA=-(grav/g.rope)*Math.sin(g.theta)-((g.ax-g.wind)/g.rope)*Math.cos(g.theta)-.48*g.omega;g.omega+=angleA*dt;g.theta+=g.omega*dt;g.theta=clamp(g.theta,-1.05,1.05)}else if(g.phase==='fall'){const o=g.dropObj;o.vy+=1100*dt;o.x+=o.vx*dt;o.y+=o.vy*dt;o.angle+=o.spin*dt;if(o.y+o.h/2>=g.platformY){o.y=g.platformY-o.h/2;evaluate();}else if(o.x< -90||o.x>450){evaluate()}}else if(g.phase==='wait'){g.wait-=dt;if(g.wait<=0){if(g.complete){finish('done');return}nextCargo()}}}
function drawBox(x,y,w,h,color,type,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle='#06152966';ctx.fillRect(-w/2+3,-h/2+4,w,h);ctx.fillStyle=color;ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeStyle='#dce6e8';ctx.lineWidth=1.6;ctx.strokeRect(-w/2,-h/2,w,h);if(type==='pipe'){ctx.fillStyle='#6289a4';for(let i=-2;i<=2;i++){ctx.beginPath();ctx.ellipse(i*13,0,6,5,0,0,Math.PI*2);ctx.fill();ctx.stroke()}}else if(type==='water'){ctx.fillStyle='#b6f8ff9c';ctx.fillRect(-w/2+4,-1,w-8,h/2-3);ctx.strokeStyle='#d1ffff';ctx.beginPath();ctx.moveTo(-w/2+4,-1);ctx.lineTo(w/2-4,-1);ctx.stroke()}else{ctx.strokeStyle='#00000055';for(let k=-w/2+8;k<w/2;k+=12){ctx.beginPath();ctx.moveTo(k,-h/2+2);ctx.lineTo(k,h/2-2);ctx.stroke()}if(type==='fragile'){ctx.fillStyle='#fff';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText('!',0,4)}}ctx.restore()}
function drawBackground(t){const w=world.w,h=world.h;const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#102941');bg.addColorStop(.7,'#47758d');bg.addColorStop(1,'#b3a07e');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle='#ffd18a';ctx.beginPath();ctx.arc(290,100,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffff14';for(let i=0;i<7;i++){const x=(i*91-(t*4)%90+500)%440-40;ctx.beginPath();ctx.ellipse(x,102+(i%3)*24,35,8,0,0,Math.PI*2);ctx.fill()}const horizon=h-111;ctx.fillStyle='#263f55';for(let i=0;i<14;i++){const bx=i*29-8,bh=30+(i*19)%53;ctx.fillRect(bx,horizon-bh,23,bh);ctx.fillStyle='#f9d68966';for(let j=0;j<3;j++)ctx.fillRect(bx+4+j*6,horizon-bh+6,2,3);ctx.fillStyle='#263f55'}ctx.fillStyle='#21485d';ctx.fillRect(0,horizon,w,54);ctx.fillStyle='#426e81';ctx.fillRect(0,horizon+54,w,h-horizon-54);ctx.strokeStyle='#8ddce04d';ctx.lineWidth=1;for(let k=0;k<9;k++){const y=horizon+65+k*14;ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<=w;x+=14)ctx.lineTo(x,y+Math.sin(x*.04+t*1.5+k)*2);ctx.stroke()}ctx.fillStyle='#3a4b5a';ctx.fillRect(0,h-39,w,39);ctx.fillStyle='#637782';ctx.fillRect(0,h-41,w,4);for(let x=4;x<w;x+=33){ctx.fillStyle='#f5d184';ctx.fillRect(x,h-18,14,3)}}
function drawCrane(){const g=game,w=world.w;ctx.strokeStyle='#76542a';ctx.lineWidth=3;ctx.strokeRect(6,31,w-12,20);ctx.fillStyle='#f8bf47';ctx.fillRect(7,32,w-14,17);ctx.strokeStyle='#a4772b';ctx.lineWidth=1.6;for(let x=12;x<w-25;x+=33){ctx.beginPath();ctx.moveTo(x,33);ctx.lineTo(x+17,48);ctx.lineTo(x+33,33);ctx.stroke()}ctx.fillStyle='#e5b359';ctx.fillRect(3,31,13,world.h-69);ctx.fillRect(w-16,31,13,world.h-69);ctx.fillStyle='#443c34';for(let y=69;y<world.h-40;y+=54){ctx.fillRect(4,y,11,5);ctx.fillRect(w-15,y,11,5)}ctx.fillStyle='#ffdb7b';ctx.fillRect(g.trolleyX-23,23,46,37);ctx.fillStyle='#23425b';ctx.fillRect(g.trolleyX-12,29,24,12);ctx.fillStyle='#1c2c38';ctx.beginPath();ctx.arc(g.trolleyX-15,61,6,0,Math.PI*2);ctx.arc(g.trolleyX+15,61,6,0,Math.PI*2);ctx.fill()}
function drawTarget(t){const g=game,y=g.platformY,w=g.targetWidth,x=g.targetX;ctx.fillStyle='#183547aa';ctx.fillRect(x-w/2-3,y-4,w+6,5);ctx.fillStyle='#9bd3ac';ctx.fillRect(x-w/2,y,w,11);ctx.strokeStyle='#d4ffe0';ctx.lineWidth=2;ctx.strokeRect(x-w/2,y,w,11);ctx.strokeStyle='#7ee9ce99';ctx.setLineDash([5,5]);ctx.strokeRect(x-w/2,y-65,w,65);ctx.setLineDash([]);ctx.fillStyle='#153f2f';ctx.font='bold 9px sans-serif';ctx.textAlign='center';ctx.fillText(mode==='tower'?'STACK HERE':'TARGET',x,y+9);if(mode==='tower'){for(let i=0;i<g.stack;i++)drawBox(x,world.h-59-10-i*21,56,20,i%2?'#e9a84b':'#ca8553','box')}}
function draw(){if(!canvas.width||!canvas.height)return;const w=world.w,h=world.h,t=game?.elapsed||performance.now()/1000;ctx.clearRect(0,0,w,h);drawBackground(t);if(!game){ctx.fillStyle='#f7cd62';ctx.fillRect(8,30,w-16,14);ctx.strokeStyle='#fce9bd';ctx.beginPath();ctx.moveTo(140,45);ctx.lineTo(160,h*.41);ctx.stroke();drawBox(160,h*.41,55,33,'#f8a44d','box');return}const g=game;drawTarget(t);if(g.phase==='carry'){const p=cargoPoint(),x=landingX();ctx.setLineDash([3,5]);ctx.strokeStyle='#fff5b55e';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(x,g.platformY);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle=Math.abs(x-g.targetX)<21?'#aaffc8':'#ffde9b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-8,g.platformY-2);ctx.lineTo(x+8,g.platformY-2);ctx.stroke();ctx.save();ctx.setLineDash([4,6]);ctx.strokeStyle='#ffffff88';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(g.trolleyX,62);ctx.lineTo(g.trolleyX,62+g.rope);ctx.stroke();ctx.restore();ctx.strokeStyle='#e5e8ed';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(g.trolleyX,62);ctx.lineTo(p.x,p.y-g.cargo.h*.4);ctx.stroke();ctx.fillStyle='#eaf4ff';ctx.beginPath();ctx.arc(p.x,p.y-g.cargo.h*.4,4,0,Math.PI*2);ctx.fill();drawBox(p.x,p.y,g.cargo.w,g.cargo.h,g.cargo.color,g.cargo.id,g.theta*.6)}else if(g.dropObj){const o=g.dropObj;drawBox(o.x,o.y,o.w,o.h,g.cargo.color,g.cargo.id,o.angle*.65)}drawCrane();if(mode==='wind'){ctx.fillStyle='#f5e1a8';ctx.font='bold 12px sans-serif';ctx.textAlign='left';ctx.fillText(`WIND ${g.wind>=0?'→':'←'} ${Math.abs(g.wind).toFixed(0)}`,20,91)}ctx.fillStyle='#ffffffae';ctx.font='11px sans-serif';ctx.textAlign='left';ctx.fillText(g.cargo.name,20,h-54)}
function frame(now){requestAnimationFrame(frame);if(!lastFrame)lastFrame=now;let dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(state==='playing'){accumulator=Math.min(.12,accumulator+dt);let steps=0;while(accumulator>=1/120&&steps++<16){step(1/120);accumulator-=1/120;if(state!=='playing')break}updateHUD()}if(noticeText&&now>noticeUntil){message.classList.remove('show');noticeText=''}draw()}
startMenu();resize();requestAnimationFrame(frame);
})();