(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#sea'),ctx=canvas.getContext('2d'),stage=$('#stage'),action=$('#actionBtn'),hint=$('#hint'),sonar=$('#sonarBtn');
const SPEC=[
 {id:'kiss',name:'シロギス',icon:'🐟',min:12,max:29,base:13,color:'#f5e7bc',rarity:'砂地の人気者'},
 {id:'haze',name:'ハゼ',icon:'🐟',min:8,max:20,base:7,color:'#ac8d61',rarity:'浅場によくいる'},
 {id:'megochi',name:'メゴチ',icon:'🐡',min:9,max:24,base:8,color:'#8e9278',rarity:'海底の住人'},
 {id:'fugu',name:'クサフグ',icon:'🐡',min:9,max:22,base:3,color:'#a8c56e',rarity:'エサ取り名人'},
 {id:'crab',name:'カニ',icon:'🦀',min:5,max:13,base:5,color:'#ed8660',rarity:'底を歩いている'},
 {id:'boot',name:'長靴',icon:'🥾',min:23,max:31,base:1,color:'#3c4a53',rarity:'海の落とし物'}
];
const THEMES={morning:{name:'朝',sky:['#fbd3a0','#b0e3e9'],sea:['#4db7d1','#176c90'],sun:'#ffe2a0'},day:{name:'昼',sky:['#73cdec','#d3f4f7'],sea:['#2ea4c4','#0b6588'],sun:'#fff5ae'},evening:{name:'夕',sky:['#f7ae7d','#786eab'],sea:['#418ba9','#153e6c'],sun:'#ffe0a0'}};
const STORE='sakamoto-kiss-v2';
function load(){try{return JSON.parse(localStorage.getItem(STORE))||{}}catch{return {}}}
const saved=load();let data={best:saved.best||{},catalog:saved.catalog||{},total:saved.total||0,sound:saved.sound!==false};
function save(){try{localStorage.setItem(STORE,JSON.stringify(data))}catch{}}
let W=300,H=350,dpr=1,last=performance.now(),animTime=0,messageUntil=0;
let mode='challenge',timeMode='morning',gear='single',phase='menu',round=180,score=0,aim=55,charge=.15,chargeDir=1,held=false,holdPointer=null,wind=0,seed=0,random=Math.random;
let fishes=[],castIndex=0,fishOn=null,doubleFish=null,fishTarget=null,biteTime=0,nibbleTime=0,waitTime=0,attract=0,bait=1,trip=[],kissCount=0,missionDone=false,sonarUntil=0,sonarReady=0,sonarText='',sonarTextUntil=0,fightT=.43,fishRun=0,slackTime=0,landHold=0;
const rig={d:0,x:0,y:0,startX:0,startY:0,flight:0,targetD:0};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
function rand(){return random()}
function mulberry32(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateKey=day.replace(/[^0-9]/g,'');
function bestKey(){return mode==='daily'?'daily-'+dateKey:mode}
function chooseButtons(group,attr,value){group.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset[attr]===value))}
function menuSync(){chooseButtons($('#modes'),'mode',mode);chooseButtons($('#times'),'time',timeMode);$$('[data-gear]').forEach(b=>{b.disabled=b.dataset.gear==='double'&&data.total<8;b.classList.toggle('selected',b.dataset.gear===gear)});$('#unlockText').textContent=data.total<8?`合計8匹で2本針解放（あと${8-data.total}匹）`:'2本針を解放済み！';$('#bestText').textContent=`自己ベスト ${data.best[bestKey()]||0}点`;$('#soundBtn').textContent=data.sound?'🔊':'🔇'}
$('#modes').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;mode=b.dataset.mode;if(mode==='daily')timeMode='morning';menuSync()});
$('#times').addEventListener('click',e=>{const b=e.target.closest('[data-time]');if(!b||mode==='daily')return;timeMode=b.dataset.time;menuSync()});
$$('[data-gear]').forEach(b=>b.addEventListener('click',()=>{if(!b.disabled){gear=b.dataset.gear;menuSync()}}));
let audio=null;
function sound(freq=440,duration=.07,volume=.035,type='sine'){if(!data.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio??=new AC();if(audio.state==='suspended')audio.resume().catch(()=>{});const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audio.currentTime);gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration+.01)}catch{}}
function buzz(pattern){try{navigator.vibrate?.(pattern)}catch{}}
$('#soundBtn').addEventListener('click',()=>{data.sound=!data.sound;save();menuSync();if(data.sound)sound()});
function say(text,kind='',seconds=1.65){hint.textContent=text;hint.className='stage-hint visible'+(kind?' '+kind:'');messageUntil=performance.now()/1000+seconds}
function updateAction(){action.className='action';const powerBar=$('#powerMeter');if(powerBar)powerBar.style.width='0';action.disabled=false;
 if(phase==='idle'){action.innerHTML='🎯 長押しでキャスト<small>パワーを狙う距離に合わせよう</small><i class="meter" id="powerMeter"></i>'}
 else if(phase==='casting'||phase==='sinking'||phase==='landed'){action.classList.add('wait');action.innerHTML=phase==='casting'?'仕掛けが飛んでいます…':phase==='sinking'?'海底へ沈んでいます…':'次のキャスト準備中…';action.disabled=true}
 else if(phase==='search'){action.classList.add('search');action.innerHTML='↩ 巻いて誘う<small>長押しで巻く・離して止める</small>'}
 else if(phase==='nibble'){action.classList.add('wait');action.innerHTML='コツコツ…前アタリ<small>まだ待て！早合わせに注意</small>'}
 else if(phase==='bite'){action.classList.add('bite');action.innerHTML='❗ 今だ！合わせる！<small>急いでタップ！</small>'}
 else if(phase==='fight'){action.classList.add('fight');action.innerHTML='🎣 巻き上げる！<small>テンションが赤なら離そう</small>'}
 else{action.classList.add('wait');action.textContent=phase==='over'?'本日の釣りは終了':'釣り場を準備中';action.disabled=true}
}
function setPhase(p){phase=p;held=false;holdPointer=null;action.classList.remove('pressed');$('#tensionBox').classList.toggle('show',p==='fight');updateAction()}
function resize(){const r=stage.getBoundingClientRect();if(r.width<1||r.height<1)return;W=r.width;H=r.height;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);rig.x=toX(rig.d);rig.y=bed(rig.d)-7}
const toX=d=>W*(.17+.77*clamp(d,0,100)/100);
const fromX=x=>clamp(Math.round((x/W-.17)/.77*100),15,100);
function bed(d){const u=clamp(d,0,100)/100;return H*(.77+.052*Math.sin(u*6.1)+.035*Math.sin(u*16+.6)-.038*u)}
function ground(d){return bed(d)-7}
function initFish(){fishes=[];const spots=[];for(let i=0;i<7;i++){let d=14+rand()*80;if(spots.some(s=>Math.abs(s-d)<9))d=clamp(d+12,14,96);spots.push(d);const count=2+Math.floor(rand()*4);for(let j=0;j<count;j++){const r=rand();let kind=r<.65?0:r<.76?1:r<.85?2:r<.94?3:r<.985?4:5;if(timeMode==='evening'&&r<.72)kind=0;if(timeMode==='day'&&r>.62&&r<.78)kind=3;const s=SPEC[kind];const d2=clamp(d+(rand()-.5)*8,6,98);fishes.push({id:fishes.length,kind,d:d2,origin:d2,size:s.min+rand()*(s.max-s.min),v:.7+rand()*.7,phase:rand()*6.28,interest:rand(),scared:0,alive:true})}}}
function start(){if(mode==='daily')timeMode='morning';seed=mode==='daily'?hash('kiss-'+dateKey):hash(String(Date.now())+'-'+Math.random());random=mulberry32(seed);wind=Math.round((rand()-.5)*9)/2;initFish();castIndex=0;round=mode==='free'?Infinity:180;score=0;aim=55;charge=.15;chargeDir=1;rig.d=0;rig.x=toX(0);rig.y=ground(0);trip=[];kissCount=0;missionDone=false;fishOn=null;doubleFish=null;fishTarget=null;sonarUntil=0;sonarReady=0;attract=0;$('#score').textContent='0';$('#aimRange').value=55;$('#aimValue').textContent='55m';$('#startOverlay').classList.add('hidden');$('#resultOverlay').classList.add('hidden');$('#catalogOverlay').classList.add('hidden');$('#weather').textContent=`${timeMode==='morning'?'🌅':timeMode==='day'?'☀️':'🌇'} ${THEMES[timeMode].name} / 風 ${wind>0?'+':''}${wind}m`;
 $('#missionHud').textContent='目標：キス3匹';$('#clock').textContent=mode==='free'?'∞':'3:00';$('#radar').innerHTML='📡 魚探を使おう<small>魚のいる距離を探そう</small>';setPhase('idle');say('海をタップして狙いを決めよう！');last=performance.now();sound(500,.09)}
$('#startBtn').addEventListener('click',start);
$('#aimRange').addEventListener('input',e=>{aim=Number(e.target.value);$('#aimValue').textContent=aim+'m'});
canvas.addEventListener('pointerdown',e=>{if(!['idle','search'].includes(phase))return;const rect=canvas.getBoundingClientRect();aim=fromX(e.clientX-rect.left);$('#aimRange').value=aim;$('#aimValue').textContent=aim+'m';if(phase==='idle')say(`${aim}m地点を狙う！`, '',.8)});
function clearHold(){held=false;action.classList.remove('pressed')}
function press(e){if(e){e.preventDefault();if(e.pointerId!==undefined){holdPointer=e.pointerId;try{action.setPointerCapture(e.pointerId)}catch{}}}if(phase==='idle'){held=true;charge=.15;chargeDir=1;action.classList.add('pressed')}
 else if(phase==='search'){held=true;action.classList.add('pressed')}
 else if(phase==='nibble'){clearHold();if(fishTarget){fishTarget.scared=5;fishTarget.d=clamp(fishTarget.d+5,5,98)}fishTarget=null;setPhase('search');say('早すぎた！魚が逃げた…','',1.2);sound(210,.15)}
 else if(phase==='bite'){hook()}
 else if(phase==='fight'){held=true;action.classList.add('pressed')}}
function release(e){if(e?.pointerId!==undefined&&holdPointer!==null&&e.pointerId!==holdPointer)return;if(phase==='idle'&&held)cast();clearHold();holdPointer=null}
action.addEventListener('pointerdown',press);action.addEventListener('pointerup',release);action.addEventListener('pointercancel',release);action.addEventListener('lostpointercapture',()=>{if(held)release()});action.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(e.code!=='Space'||e.repeat||!['idle','search','nibble','bite','fight'].includes(phase)||!$('#catalogOverlay').classList.contains('hidden')||!$('#startOverlay').classList.contains('hidden'))return;if(['BUTTON','INPUT'].includes(document.activeElement?.tagName))return;e.preventDefault();press()});
window.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();release()}});
function cast(){const p=charge;clearHold();rig.targetD=clamp(15+85*p+wind*1.4,10,100);rig.d=0;rig.flight=0;rig.startX=toX(0);rig.startY=H*.22;rig.x=rig.startX;rig.y=rig.startY;castIndex++;bait=1;fishTarget=null;doubleFish=null;attract=Math.abs(rig.targetD-aim)<=6?1.5:1;setPhase('casting');say(`${Math.round(rig.targetD)}m！ ${Math.abs(rig.targetD-aim)<=6?'ジャストキャスト！':'着底を待とう'}`,'',1.1);sound(520,.13);buzz(25)}
function sonarClick(){if(['menu','over'].includes(phase))return;if(sonarReady>0)return;sonarReady=16;sonarUntil=5;const groups=[];const live=fishes.filter(f=>f.alive);for(const f of live){const d=Math.round(f.d/10)*10;const item=groups.find(g=>g.d===d);if(item)item.n++;else groups.push({d,n:1})}groups.sort((a,b)=>b.n-a.n);sonarText=groups.slice(0,3).map(g=>`${g.d}m付近 ${g.n}反応`).join(' / ')||'魚影なし';sonarTextUntil=5;$('#radar').innerHTML='📡 '+sonarText.split(' / ')[0]+'<small>'+((groups[1]&&groups[1].d+'m付近にも反応')||'魚影が見える！')+'</small>';say('魚探：'+sonarText,'',2.3);sound(720,.08);setTimeout(()=>sound(980,.1),110)}
sonar.addEventListener('click',sonarClick);
function nearestFish(){let chosen=null,min=Infinity;for(const f of fishes){if(!f.alive||f.scared>0)continue;const d=Math.abs(f.d-rig.d);if(d<min&&d<9){chosen=f;min=d}}return chosen}
function hook(){if(phase!=='bite')return;if(!fishTarget||!fishTarget.alive){setPhase('search');return}fishOn=fishTarget;fishTarget=null;doubleFish=null;fightT=.43;slackTime=0;landHold=0;fishRun=0;rig.d=clamp(rig.d,3,100);setPhase('fight');say('乗った！ テンションに注意！','',1.4);sound(810,.14);buzz([40,30,75]);if(gear==='double'){const candidates=fishes.filter(f=>f.alive&&f!==fishOn&&f.scared<=0&&Math.abs(f.d-rig.d)<5);if(candidates.length&&rand()<.57){doubleFish=candidates[Math.floor(rand()*candidates.length)];say('ダブルヒット！！ 2匹が走る！','alert',1.7);fightT=.55}}}
function flee(reason){if(fishOn){fishOn.scared=5;fishOn.d=clamp(fishOn.d+3,4,99)}if(doubleFish){doubleFish.scared=5;doubleFish.d=clamp(doubleFish.d+2,4,99)}fishOn=null;doubleFish=null;fishTarget=null;setPhase('search');say(reason,'',1.4);sound(190,.19);buzz(80)}
function catchOne(f){const s=SPEC[f.kind];f.alive=false;const pts=Math.round(f.size*s.base)+(s.id==='kiss'&&f.size>=23?100:0);trip.push({kind:f.kind,name:s.name,icon:s.icon,size:f.size,points:pts});score+=pts;data.total++;const prior=data.catalog[s.id]||{count:0,max:0};data.catalog[s.id]={count:prior.count+1,max:Math.max(prior.max,f.size)};if(s.id==='kiss')kissCount++;return pts}
function land(){const first=fishOn,second=doubleFish;if(!first){setPhase('idle');return}let pts=catchOne(first),count=1;if(second&&second.alive){pts+=catchOne(second);count++}if(count===2){score+=150;pts+=150}$('#score').textContent=score;fishOn=null;doubleFish=null;fishTarget=null;save();setPhase('landed');$('#missionHud').textContent=`目標：キス ${Math.min(3,kissCount)}/3匹`;if(kissCount>=3&&!missionDone){missionDone=true;score+=300;pts+=300;$('#score').textContent=score}const names=trip.slice(-count).map(f=>`${f.name} ${f.size.toFixed(1)}cm`).join(' ＆ ');say(`${count===2?'ダブル！ ':''}${names}  +${pts}点${missionDone&&kissCount===3?' 🎖️':''}`,'',2.25);sound(740,.13);setTimeout(()=>sound(980,.17),125);buzz([35,40,35]);landHold=1.85}
function over(){if(phase==='over')return;setPhase('over');round=0;$('#clock').textContent='0:00';const key=bestKey(),old=data.best[key]||0,isNew=score>old;if(isNew)data.best[key]=score;save();const rows=trip.map(f=>`<div class="catch-item"><span class="icon">${f.icon}</span><span class="detail"><b>${f.name} ${f.size.toFixed(1)}cm</b><br><small>${SPEC[f.kind].rarity}</small></span><b>+${f.points}</b></div>`).join('');$('#resultCard').innerHTML=`<div class="eyebrow">FISHING RESULT</div><h2>🎣 本日の釣果</h2><div class="center"><div class="score-large">${score.toLocaleString()} 点</div>${isNew?'<div class="record">🏆 自己ベスト更新！</div>':''}<p>${trip.length}匹 / キス ${kissCount}匹 / ベスト ${Number(data.best[key]||0).toLocaleString()}点</p></div><div class="mission">${missionDone?'🎖️ ミッション達成！ キス3匹 +300点':'🎯 キス3匹ミッション：'+kissCount+'/3匹'}${mode==='daily'?'　/　日替わり '+dateKey:''}</div><div class="catch-list">${rows||'<p>今回はボウズ。魚探を使って群れの距離を狙おう。</p>'}</div><div class="row-buttons"><button class="primary" id="againBtn">もう一度！</button><button class="secondary" id="homeBtn">モード選択</button></div>`;$('#resultOverlay').classList.remove('hidden');$('#againBtn').addEventListener('click',start);$('#homeBtn').addEventListener('click',showMenu);sound(440,.15)}
function showMenu(){clearHold();$('#resultOverlay').classList.add('hidden');$('#catalogOverlay').classList.add('hidden');setPhase('menu');menuSync();$('#startOverlay').classList.remove('hidden');last=performance.now()}
$('#menuBtn').addEventListener('click',showMenu);
function showCatalog(){clearHold();const grid=$('#catalogGrid');grid.innerHTML=SPEC.map(s=>{const item=data.catalog[s.id],known=!!item;return `<div class="species-card ${known?'':'locked'}"><div class="fish-icon">${known?s.icon:'❔'}</div><b>${known?s.name:'？？？'}</b><small>${known?s.rarity:'まだ釣っていない'}</small><small>${known?`釣果 ${item.count}匹 / 最大 ${item.max.toFixed(1)}cm`:'？？？'}</small></div>`}).join('');$('#catalogTotal').textContent=`累計 ${data.total}匹　図鑑 ${Object.keys(data.catalog).filter(k=>data.catalog[k].count>0).length}/${SPEC.length} 種類`;$('#catalogOverlay').classList.remove('hidden');last=performance.now()}
$('#catalogBtn').addEventListener('click',showCatalog);$('#closeCatalog').addEventListener('click',()=>{$('#catalogOverlay').classList.add('hidden');last=performance.now()});
function update(dt){animTime+=dt;if(phase==='menu'||phase==='over'||!$('#catalogOverlay').classList.contains('hidden'))return;
 if(Number.isFinite(round)){round=Math.max(0,round-dt);const sec=Math.ceil(round);$('#clock').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(round<=0){over();return}}
 sonarReady=Math.max(0,sonarReady-dt);sonarUntil=Math.max(0,sonarUntil-dt);sonarTextUntil=Math.max(0,sonarTextUntil-dt);sonar.disabled=sonarReady>0;$('#sonarLabel').textContent=sonarReady>0?Math.ceil(sonarReady)+'秒':'魚探';if(sonarReady<=0)sonar.classList.add('ready');else sonar.classList.remove('ready');
 if(sonarTextUntil<=0&&sonarUntil<=0)$('#radar').innerHTML=phase==='fight'?'🎣 魚とファイト中<small>赤ゾーンに注意！</small>':`📡 距離 ${Math.round(rig.d)}m<small>${phase==='search'?'巻いて止めて誘おう':'魚探で群れを見つけよう'}</small>`;
 for(const f of fishes){if(!f.alive)continue;f.phase+=dt*(.9+f.v*.3);f.scared=Math.max(0,f.scared-dt);if(f.scared>0){f.d=clamp(f.d+dt*f.v*1.8,5,99);continue}if(phase==='search'||phase==='nibble'||phase==='bite'){if(f===fishTarget)continue;const diff=rig.d-f.d;const distance=Math.abs(diff);if(distance<8&&bait>0){const factor=(phase==='search'?(held?.42:1.2):.55)*attract;if(distance>1)f.d=clamp(f.d+Math.sign(diff)*dt*f.v*factor,4,99)}else f.d=clamp(f.d+Math.sin(f.phase*.3)*dt*.17,4,99)}else if(phase==='idle'){f.d=clamp(f.d+Math.sin(f.phase*.4)*dt*.25,4,99)}}
 if(phase==='idle'&&held){charge+=chargeDir*dt*.73;if(charge>=1){charge=1;chargeDir=-1}else if(charge<=.15){charge=.15;chargeDir=1}const meter=$('#powerMeter');if(meter)meter.style.width=Math.round(charge*100)+'%';const predicted=clamp(15+85*charge+wind*1.4,10,100);action.setAttribute('aria-label',`現在の飛距離 ${Math.round(predicted)}メートル`)}
 else if(phase==='casting'){rig.flight+=dt;const t=clamp(rig.flight/1.03,0,1);rig.d=rig.targetD*t;rig.x=toX(rig.d);rig.y=rig.startY+(ground(rig.targetD)-rig.startY)*t-Math.sin(Math.PI*t)*H*.23;if(t>=1){rig.d=rig.targetD;rig.y=H*.38;rig.flight=0;setPhase('sinking')}}
 else if(phase==='sinking'){rig.y+=dt*H*.56;if(rig.y>=ground(rig.d)){rig.y=ground(rig.d);setPhase('search');say('着底！ 巻いて止めて魚を誘おう','',1.3);sound(230,.07)}}
 else if(phase==='search'){attract=Math.max(1,attract-dt*.13);if(held){rig.d=Math.max(1,rig.d-dt*8.4);rig.x=toX(rig.d);rig.y=ground(rig.d);if(Math.random()<dt*3)sound(250,.022,.012)}const f=nearestFish();if(f&&Math.abs(f.d-rig.d)<1.45&&bait>0){waitTime+=dt*(held?.58:1.5)*attract;if(waitTime>.43){fishTarget=f;nibbleTime=.48+rand()*.35;setPhase('nibble');say('コツ…コツ…！ まだ待て！','',1.1);sound(315,.05);setTimeout(()=>sound(350,.045),100);buzz([20,90,20]);waitTime=0}}else waitTime=Math.max(0,waitTime-dt*.3);if(rig.d<=1){setPhase('idle');rig.d=0;waitTime=0;say('手前まで来た。次のポイントを狙おう！','',1.15)}}
 else if(phase==='nibble'){nibbleTime-=dt;if(nibbleTime<=0){biteTime=1.35;setPhase('bite');say('ブルブルッ！！ 今だ！','alert',1.35);sound(600,.08);setTimeout(()=>sound(790,.1),90);buzz([50,40,65])}}
 else if(phase==='bite'){biteTime-=dt;if(biteTime<=0){if(fishTarget){fishTarget.scared=4;fishTarget.d=clamp(fishTarget.d+4,5,98)}fishTarget=null;setPhase('search');say('あっ、遅かった！','',1);sound(180,.15)}}
 else if(phase==='fight'){fishRun+=dt;const burst=Math.sin(fishRun*3.1)> .76? .26:0;const pull=.10+burst+(doubleFish?.11:0);fightT=clamp(fightT+dt*(pull+(held?.47:-.44)),0,1.11);if(held&&fightT>.12&&fightT<.91){rig.d=Math.max(0,rig.d-dt*(11.5+(1-fightT)*2));rig.x=toX(rig.d);rig.y=ground(rig.d)-4}if(fightT<.1)slackTime+=dt;else slackTime=0;$('#tensionNeedle').style.left=clamp(fightT*100,0,100)+'%';$('#tensionText').textContent=fightT>.87?'危険！離せ！':fightT<.21?'ゆるい！巻け！':burst?'魚が走った！':'安全';if(fightT>=1.02)flee('糸が切れた！！');else if(slackTime>.85)flee('糸が緩んでバレた！');else if(rig.d<=.5)land()}
 else if(phase==='landed'){landHold-=dt;if(landHold<=0){setPhase('idle');rig.d=0;rig.x=toX(0);waitTime=0;menuSync();say('次はどの群れを狙う？','',1.3)}}
}
function path(points,stroke,width=1){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke()}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);ctx.fill()}
function paint(){if(!W||!H)return;const theme=THEMES[timeMode],surf=H*.31;let sky=ctx.createLinearGradient(0,0,0,surf);sky.addColorStop(0,theme.sky[0]);sky.addColorStop(1,theme.sky[1]);ctx.fillStyle=sky;ctx.fillRect(0,0,W,surf);let sea=ctx.createLinearGradient(0,surf,0,H);sea.addColorStop(0,theme.sea[0]);sea.addColorStop(1,theme.sea[1]);ctx.fillStyle=sea;ctx.fillRect(0,surf,W,H-surf);ellipse(W*.78,timeMode==='evening'?surf*.73:surf*.34,Math.max(12,H*.043),Math.max(12,H*.043),theme.sun);
 ctx.globalAlpha=.4;for(let k=0;k<5;k++){path(Array.from({length:Math.ceil(W/20)+1},(_,i)=>{const x=i*20;return[x,surf+9+k*14+Math.sin(i*.8+k+animTime*.9)*2]}),'#dcf8fa',1.1)}ctx.globalAlpha=1;
 ctx.beginPath();ctx.moveTo(0,bed(0));for(let x=0;x<=W+8;x+=8)ctx.lineTo(x,bed(fromX(x)));ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();const sand=ctx.createLinearGradient(0,H*.71,0,H);sand.addColorStop(0,'#f2daa3');sand.addColorStop(1,'#b7986a');ctx.fillStyle=sand;ctx.fill();ctx.strokeStyle='#f8eac2';ctx.lineWidth=2;ctx.stroke();
 for(let i=0;i<28;i++){const d=10+i*3.2,x=toX(d),y=bed(d)+8+(i*11%23);ellipse(x,y,2.5+(i%4),1.2,'#a58b62aa')}
 for(let i=0;i<4;i++){const d=22+i*23,x=toX(d),y=bed(d)-2;path([[x,y],[x-3,y-8],[x+3,y-13]],'#4f9b82',2);path([[x,y],[x+4,y-8]],'#4f9b82',2)}
 ctx.fillStyle='#c7bfb0';ctx.beginPath();ctx.moveTo(0,surf*.8);ctx.lineTo(W*.15,surf*.99);ctx.lineTo(W*.13,bed(0));ctx.lineTo(0,bed(0)+7);ctx.closePath();ctx.fill();for(let i=0;i<6;i++)path([[0,surf*.88+i*H*.074],[W*.14,surf*.96+i*H*.071]],'#9b968a',2);
 ctx.save();ctx.translate(W*.085,surf*.87);const s=clamp(H/460,.62,1.15);ctx.scale(s,s);ctx.lineCap='round';path([[0,-20],[0,8],[11,32]],'#1e4050',5);path([[0,8],[-13,30]],'#1e4050',5);path([[0,-11],[20,3],[65,-40]],'#1e4050',4);ellipse(0,-28,9,9,'#1e4050');path([[19,3],[74,-36]],'#714932',3);ctx.restore();
 if(phase==='idle'||phase==='menu'){const x=toX(aim),y=ground(aim);ctx.setLineDash([4,5]);path([[x,surf+12],[x,y]],'#ffffffa8',1);ctx.setLineDash([]);ellipse(x,y,8,3,'#fff2a7aa');ctx.fillStyle='#fff';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(`🎯 ${aim}m`,clamp(x,32,W-32),surf+16)}
 for(let i=0;i<7;i++){const members=fishes.filter(f=>f.alive&&Math.abs(f.origin-(14+i*11))<6);if(members.length===0)continue;const x=members.reduce((sum,f)=>sum+toX(f.d),0)/members.length,yy=surf+10;ctx.strokeStyle='#f4ffff8a';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(x,yy,6+Math.sin(animTime*2+i)*2,2,0,0,Math.PI*2);ctx.stroke()}
 const searching=phase==='search'||phase==='nibble'||phase==='bite'||phase==='fight';for(const f of fishes){if(!f.alive)continue;const visible=sonarUntil>0||searching&&Math.abs(f.d-rig.d)<17;if(!visible)continue;const x=toX(f.d),y=ground(f.d)-11-Math.sin(f.phase)*3,sz=clamp(W/450,.55,1)*(.8+f.size/35);ctx.save();ctx.globalAlpha=sonarUntil>0?.86:.37;ctx.translate(x,y);ctx.scale(sz,sz);ellipse(0,0,11,4.5,SPEC[f.kind].color);ctx.fillStyle=SPEC[f.kind].color;ctx.beginPath();ctx.moveTo(-8,0);ctx.lineTo(-17,-5);ctx.lineTo(-17,5);ctx.closePath();ctx.fill();ellipse(6,-1,1,1,'#12394a');ctx.restore();if(sonarUntil>0){ctx.strokeStyle='#adfff3a0';ctx.beginPath();ctx.arc(x,y,9+Math.sin(animTime*6)*2,0,Math.PI*2);ctx.stroke()}}
 if(!['idle','menu','over','landed'].includes(phase)){const tipX=W*.085+74*clamp(H/460,.62,1.15),tipY=surf*.87-36*clamp(H/460,.62,1.15);path([[tipX,tipY],[rig.x,rig.y]],'#fcffffdd',1.4);ellipse(rig.x,rig.y,4.5,6,'#56616a');path([[rig.x,rig.y],[rig.x+13,rig.y+2]],'#f4ebcb',1);ellipse(rig.x+15,rig.y+2,3,2.5,'#ff8c66');if(fishOn){const color=SPEC[fishOn.kind].color;ellipse(rig.x+20,rig.y-5,13,5,color);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(rig.x+9,rig.y-5);ctx.lineTo(rig.x+2,rig.y-11);ctx.lineTo(rig.x+2,rig.y);ctx.fill()}}
 ctx.fillStyle='#ffffffaa';ctx.textAlign='center';ctx.font='800 10px system-ui';for(let d=0;d<=100;d+=20){const x=toX(d);if(x<10||x>W-10)continue;ctx.fillText(d+'m',x,bed(d)+25)}
 if(phase!=='idle'&&phase!=='menu'&&phase!=='over'){ctx.textAlign='right';ctx.font='900 11px system-ui';ctx.fillStyle='white';ctx.fillText(`仕掛け ${Math.round(rig.d)}m`,W-9,surf-7)}
}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(document.visibilityState!=='hidden'){update(dt);paint()}if(messageUntil&&now/1000>messageUntil){hint.classList.remove('visible','alert');messageUntil=0}requestAnimationFrame(frame)}
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.visibilityState==='hidden')clearHold()});
menuSync();resize();requestAnimationFrame(frame);
})();