(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],canvas=$('#sea'),ctx=canvas.getContext('2d'),stage=$('#stage'),action=$('#actionBtn'),sonar=$('#sonarBtn'),hint=$('#hint');
const STYLE=document.createElement('link');STYLE.rel='stylesheet';STYLE.href='./style-v3.css';document.head.append(STYLE);
const SPEC=[{id:'kiss',name:'シロギス',icon:'🐟',min:12,max:29,base:13,color:'#f5e7bc',rarity:'砂地の人気者'},{id:'haze',name:'ハゼ',icon:'🐟',min:8,max:20,base:7,color:'#ac8d61',rarity:'浅場の魚'},{id:'megochi',name:'メゴチ',icon:'🐡',min:9,max:24,base:8,color:'#8e9278',rarity:'海底の住人'},{id:'fugu',name:'クサフグ',icon:'🐡',min:9,max:22,base:3,color:'#a8c56e',rarity:'エサ取り名人'},{id:'crab',name:'カニ',icon:'🦀',min:5,max:13,base:5,color:'#ed8660',rarity:'底を歩いている'},{id:'boot',name:'長靴',icon:'🥾',min:23,max:31,base:1,color:'#3c4a53',rarity:'海の落とし物'}];
const THEMES={morning:{name:'朝',sky:['#fbd3a0','#b0e3e9'],sea:['#4db7d1','#176c90']},day:{name:'昼',sky:['#73cdec','#d3f4f7'],sea:['#2ea4c4','#0b6588']},evening:{name:'夕',sky:['#f7ae7d','#786eab'],sea:['#418ba9','#153e6c']}};
const STORE='sakamoto-kiss-v2',clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function read(){try{return JSON.parse(localStorage.getItem(STORE))||{}}catch{return {}}}const saved=read();const data={best:saved.best||{},catalog:saved.catalog||{},total:saved.total||0,sound:saved.sound!==false,tutorialDone:!!saved.tutorialDone};function save(){try{localStorage.setItem(STORE,JSON.stringify(data))}catch{}}
function hash(s){let h=2166136261;for(const c of s){h=Math.imul(h^c.charCodeAt(0),16777619)}return h>>>0}function generator(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}let random=Math.random;const rand=()=>random();
const dateKey=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replace(/[^0-9]/g,'');
let mode='challenge',timeMode='morning',gear='single',phase='menu',W=300,H=360,dpr=1,last=performance.now(),elapsed=0,round=180,score=0,bonusTotal=0,missionBonus=0,rivalScore=0,rivalClock=0,aim=55,charge=0,chargeDir=1,wind=0,held=false,holdPointer=null,sonarReady=0,sonarUntil=0,sonarTextUntil=0,messageUntil=0,anim=0,fishTarget=null,fishOn=null,doubleFish=null,nibbleTime=0,biteTime=0,waitTime=0,attract=1,trip=[],kissCount=0,missionDone=false,combo=0,fever=0,landHold=0,fightT=.43,fishRun=0,slackTime=0,training=false,tutorialStep=0,firstCatch=false,schools=[],fishes=[],nextFishId=0,castIndex=0;
const rig={d:0,x:0,y:0,targetD:0,flight:0,startY:0};
// Keep the existing page and browser-local save, augmenting only the controls required for the new rules.
$('#modes').insertAdjacentHTML('afterbegin','<button class="choice" data-mode="quick"><span>⚡</span>120秒爆釣</button>');
$('.aim').insertAdjacentHTML('beforeend','<div class="cast-guide" id="castGuide" aria-live="off"><div class="guide-copy"><span id="castEstimate">予測 15m</span><span id="castDifference">目標 55m</span></div><div class="guide-track"><i id="guideTarget"></i><b id="guideCurrent"></b></div></div>');
$('.top').insertAdjacentHTML('beforeend','<div class="stat rival-stat hidden" id="rivalBox"><small>坂本</small><strong id="rivalScore">0</strong></div>');
$('#stage').insertAdjacentHTML('beforeend','<div class="combo-banner hidden" id="comboBanner" aria-live="polite"></div><div class="tutorial-banner hidden" id="tutorialBanner" aria-live="polite"></div>');
$('.controls').insertAdjacentHTML('afterend','<button id="finishBtn" class="finish-btn hidden">釣りを終えて釣果を見る</button>');
$('.instructions').innerHTML='🎯 魚探で群れを探す → 距離を決める → 長押しで予測距離を合わせて投げる。<br>🐟 着底後は長押しで巻く・離して止める。コツコツは待ち、ブルブルッでタップ！<br>🎣 掛かったら赤ゾーンで離し、緩いときは巻こう。連続ヒットでコンボ！';
$('.footer-note').textContent='釣果・図鑑・初回練習の記録はこのブラウザ内だけに保存されます';
const dailyHelp=document.createElement('small');dailyHelp.id='dailyHelp';dailyHelp.className='daily-help hidden';dailyHelp.textContent='日替わりは朝固定・同じ初期配置です。順位はオンライン共有されません。';$('#times').after(dailyHelp);
const bestKey=()=>mode==='daily'?'daily-'+dateKey:mode;function chosen(group,attr,value){group.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset[attr]===value))}function menuSync(){chosen($('#modes'),'mode',mode);chosen($('#times'),'time',timeMode);$$('#times button').forEach(b=>{b.disabled=mode==='daily';b.title=mode==='daily'?'日替わりは朝固定':''});dailyHelp.classList.toggle('hidden',mode!=='daily');$$('[data-gear]').forEach(b=>{b.disabled=b.dataset.gear==='double'&&data.total<8;b.classList.toggle('selected',b.dataset.gear===gear)});$('#unlockText').textContent=data.total<8?`合計8匹で2本針解放（あと${8-data.total}匹）`:'2本針を解放済み！';$('#bestText').textContent=`自己ベスト ${Number(data.best[bestKey()]||0).toLocaleString()}点`;$('#soundBtn').textContent=data.sound?'🔊':'🔇'}
$('#modes').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;mode=b.dataset.mode;if(mode==='daily')timeMode='morning';menuSync()});$('#times').addEventListener('click',e=>{const b=e.target.closest('[data-time]');if(!b||mode==='daily')return;timeMode=b.dataset.time;menuSync()});$$('[data-gear]').forEach(b=>b.addEventListener('click',()=>{if(!b.disabled){gear=b.dataset.gear;menuSync()}}));
let audio=null;function sound(freq=440,dur=.08){if(!data.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio??=new AC();if(audio.state==='suspended')audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur+.01)}catch{}}function buzz(pattern){try{navigator.vibrate?.(pattern)}catch{}}$('#soundBtn').addEventListener('click',()=>{data.sound=!data.sound;save();menuSync();if(data.sound)sound()});
function say(text,alert=false,sec=1.6){hint.textContent=text;hint.className='stage-hint visible'+(alert?' alert':'');messageUntil=performance.now()/1000+sec}function tutorial(text){$('#tutorialBanner').textContent=text;$('#tutorialBanner').classList.toggle('hidden',!training||!text)}
function setPhase(p){phase=p;held=false;holdPointer=null;action.classList.remove('pressed');$('#tensionBox').classList.toggle('show',p==='fight');action.className='action';action.disabled=false;action.removeAttribute('aria-label');$('#castGuide').classList.toggle('active',p==='idle');const bar='<i class="meter" id="powerMeter"></i>';if(p==='idle'){action.innerHTML='🎯 長押しでキャスト<small>予測と目標を合わせて離す</small>'+bar;action.setAttribute('aria-label','長押しで飛距離を合わせ、離すとキャスト')}else if(p==='search'){action.classList.add('search');action.innerHTML='↩ 巻いて誘う<small>長押しで巻く・離すと止める</small>'}else if(p==='nibble'){action.classList.add('wait');action.innerHTML='コツコツ…まだ待つ！<small>ブルブルッで合わせよう</small>'}else if(p==='bite'){action.classList.add('bite');action.innerHTML='❗ 今だ！合わせる！<small>急いでタップ！</small>'}else if(p==='fight'){action.classList.add('fight');action.innerHTML='🎣 巻き上げる！<small>赤なら離す・緩いなら巻く</small>'}else{action.classList.add('wait');action.textContent=({casting:'仕掛けが飛んでいます…',sinking:'着底を待とう…',landed:'次のキャスト準備中…',over:'本日の釣りは終了',menu:'釣り場を準備中'})[p]||'準備中';action.disabled=true}}
function toX(d){return W*(.17+.77*clamp(d,0,100)/100)}function fromX(x){return clamp(Math.round((x/W-.17)/.77*100),15,100)}function bed(d){const u=clamp(d,0,100)/100;return H*(.77+.05*Math.sin(u*6.1)+.035*Math.sin(u*16+.6)-.038*u)}const ground=d=>bed(d)-7;
function resize(){const r=stage.getBoundingClientRect();if(!r.width||!r.height)return;W=r.width;H=r.height;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);rig.x=toX(rig.d);rig.y=ground(rig.d)}
function predicted(p){return clamp(15+85*p+wind*5.6*p*(1-p),15,100)}function guide(){const d=predicted(charge),difference=Math.round(Math.abs(d-aim)),good=difference<=6;$('#castEstimate').textContent=`予測 ${Math.round(d)}m`;$('#castDifference').textContent=good?'ジャストゾーン！':`目標 ${aim}m / 差 ${difference}m`;$('#castGuide').classList.toggle('perfect',good);$('#guideTarget').style.left=aim+'%';$('#guideCurrent').style.left=d+'%';const bar=$('#powerMeter');if(bar)bar.style.width=Math.round(charge*100)+'%';if(phase==='idle'&&held)action.setAttribute('aria-label',`予測飛距離 ${Math.round(d)}メートル、目標 ${aim}メートル`)}
function setAim(v){aim=clamp(Math.round(Number(v)||55),15,100);$('#aimRange').value=aim;$('#aimValue').textContent=aim+'m';guide()}$('#aimRange').addEventListener('input',e=>setAim(e.target.value));canvas.addEventListener('pointerdown',e=>{if(phase!=='idle'&&phase!=='search')return;const r=canvas.getBoundingClientRect();setAim(fromX(e.clientX-r.left));if(phase==='idle')say(`${aim}m地点を狙う！`,false,.8)});
function addSchool(center,count,forced=false){const school={center,origin:center,speed:(rand()<.5?-1:1)*(.13+rand()*.18),members:[],feverUntil:0,triggered:false};schools.push(school);for(let j=0;j<count;j++){const r=rand();let kind=r<.65?0:r<.76?1:r<.85?2:r<.94?3:r<.985?4:5;if(timeMode==='evening'&&r<.72)kind=0;if(timeMode==='day'&&r>.62&&r<.78)kind=3;if(forced&&j===0)kind=0;const s=SPEC[kind],giant=kind===0&&!forced&&rand()<.012;const f={id:nextFishId++,kind,giant,school,offset:(rand()-.5)*7,d:center,origin:center,size:giant?30+rand()*6:s.min+rand()*(s.max-s.min),v:.7+rand()*.7,phase:rand()*6.28,scared:0,alive:true};school.members.push(f);fishes.push(f)}return school}
function initializeFish(){schools=[];fishes=[];nextFishId=0;for(let i=0;i<7;i++)addSchool(clamp(15+i*12+(rand()-.5)*4,14,95),2+Math.floor(rand()*4),training&&i===3)}
function start(){training=!data.tutorialDone&&mode!=='daily';firstCatch=false;tutorialStep=0;if(mode==='daily')timeMode='morning';random=generator(mode==='daily'?hash('kiss-'+dateKey):hash(String(Date.now())+'-'+Math.random()));wind=Math.round((rand()-.5)*9)/2;initializeFish();castIndex=0;round=mode==='free'?Infinity:mode==='quick'?120:180;elapsed=0;score=0;bonusTotal=0;missionBonus=0;rivalScore=0;rivalClock=16;combo=0;maxCombo=0;fever=0;aim=55;charge=0;chargeDir=1;rig.d=0;rig.x=toX(0);rig.y=ground(0);trip=[];kissCount=0;missionDone=false;fishOn=null;doubleFish=null;fishTarget=null;sonarUntil=0;sonarReady=0;waitTime=0;attract=1;$('#score').textContent='0';$('#rivalScore').textContent='0';$('#rivalBox').classList.toggle('hidden',mode==='free');$('#finishBtn').classList.toggle('hidden',mode!=='free');$('#comboBanner').classList.add('hidden');$('#startOverlay').classList.add('hidden');$('#resultOverlay').classList.add('hidden');$('#catalogOverlay').classList.add('hidden');$('#weather').textContent=`${timeMode==='morning'?'🌅':timeMode==='day'?'☀️':'🌇'} ${THEMES[timeMode].name} / 風 ${wind>0?'+':''}${wind}m`;$('#missionHud').textContent='目標：キス 0/3匹';$('#clock').textContent=mode==='free'?'∞':mode==='quick'?'2:00':'3:00';$('#radar').innerHTML='📡 魚探を使おう<small>群れを狙って爆釣！</small>';setPhase('idle');setAim(55);guide();last=performance.now();if(training)tutorial('① 魚探を押そう。群れの位置が見えるよ！');else say('魚探で群れを見つけよう！');if(mode==='quick')sonarClick(true);sound(510,.09)}
$('#startBtn').addEventListener('click',start);
function sonarClick(auto=false){if(['menu','over'].includes(phase)||sonarReady>0)return;sonarReady=auto?10:16;sonarUntil=5;const groups=schools.map(s=>({d:Math.round(s.center),n:s.members.filter(f=>f.alive).length})).filter(s=>s.n>0).sort((a,b)=>b.n-a.n);const top=groups.slice(0,3);const description=top.map(g=>`${g.d}m付近 ${g.n}反応`).join(' / ')||'魚影なし';sonarTextUntil=5;$('#radar').innerHTML='📡 '+(top[0]?`${top[0].d}m付近 ${top[0].n}匹`:'魚影なし')+'<small>'+(top[1]?`${top[1].d}m付近にも反応`:'群れを追いかけよう')+'</small>';say('魚探：'+description,false,2.4);sound(720,.08);if(training&&tutorialStep===0){tutorialStep=1;tutorial('② 海をタップし、魚探で見つけた距離を狙おう！');if(top[0])setAim(top[0].d)}if(auto)say('120秒勝負！ 魚探で群れを発見！',false,2.1)}sonar.addEventListener('click',()=>sonarClick());
function cancelHold(){held=false;holdPointer=null;action.classList.remove('pressed')}
function press(e){if(e){e.preventDefault();if(e.pointerId!==undefined){if(holdPointer!==null&&holdPointer!==e.pointerId)return;holdPointer=e.pointerId;try{action.setPointerCapture(e.pointerId)}catch{}}}if(phase==='idle'){held=true;charge=0;chargeDir=1;action.classList.add('pressed');if(training&&tutorialStep<=1){tutorialStep=2;tutorial('③ 予測と目標の距離が近づいたら、指を離そう！')}}else if(phase==='search'){held=true;action.classList.add('pressed')}else if(phase==='nibble'){fishTarget&&(fishTarget.scared=5);fishTarget=null;combo=0;setPhase('search');say('早合わせ！ ブルブルッまで待とう');sound(210,.15)}else if(phase==='bite')hook();else if(phase==='fight'){held=true;action.classList.add('pressed')}}
function release(e){if(e?.pointerId!==undefined&&holdPointer!==null&&e.pointerId!==holdPointer)return;const shouldCast=phase==='idle'&&held;cancelHold();if(shouldCast)cast()}action.addEventListener('pointerdown',press);action.addEventListener('pointerup',release);action.addEventListener('pointercancel',cancelHold);action.addEventListener('lostpointercapture',cancelHold);action.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(e.code!=='Space'||e.repeat||!['idle','search','nibble','bite','fight'].includes(phase)||!$('#catalogOverlay').classList.contains('hidden')||!$('#startOverlay').classList.contains('hidden')||['BUTTON','INPUT'].includes(document.activeElement?.tagName))return;e.preventDefault();press()});window.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();release()}});
function cast(){const d=predicted(charge);rig.targetD=d;rig.d=0;rig.flight=0;rig.startY=H*.22;rig.x=toX(0);rig.y=rig.startY;castIndex++;fishTarget=null;doubleFish=null;waitTime=0;attract=Math.abs(d-aim)<=6?1.5:1;setPhase('casting');say(`${Math.round(d)}m！ ${Math.abs(d-aim)<=6?'ジャストキャスト！':'着底を待とう'}`,false,1.1);if(training){tutorialStep=3;tutorial('④ 着底したら巻いて止めて、魚を誘おう！')}sound(520,.13);buzz(25)}
function nearestFish(){let best=null,dist=Infinity;for(const f of fishes){if(!f.alive||f.scared>0)continue;const d=Math.abs(f.d-rig.d);if(d<dist&&d<9){dist=d;best=f}}return best}
function hook(){if(phase!=='bite')return;if(!fishTarget||!fishTarget.alive){setPhase('search');return}fishOn=fishTarget;fishTarget=null;doubleFish=null;fightT=.43;slackTime=0;fishRun=0;setPhase('fight');say(fishOn.giant?'幻の30cm超え！ 糸を切るな！':'乗った！ テンションに注意！',fishOn.giant,1.5);if(training)tutorial('⑥ 赤ゾーンで指を離す。緩いときは長押し！');sound(810,.14);buzz([40,30,75]);if(gear==='double'){const candidates=fishes.filter(f=>f.alive&&f!==fishOn&&f.scared<=0&&Math.abs(f.d-rig.d)<5);if(candidates.length&&rand()<.57){doubleFish=candidates[Math.floor(rand()*candidates.length)];fightT=.55;say('ダブルヒット！！',true,1.7)}}}
function flee(reason){if(fishOn){fishOn.scared=5;fishOn.d=clamp(fishOn.d+3,4,99)}if(doubleFish){doubleFish.scared=5;doubleFish.d=clamp(doubleFish.d+2,4,99)}fishOn=null;doubleFish=null;fishTarget=null;combo=0;setPhase('search');say(reason,false,1.5);sound(190,.17);buzz(80)}
function recordCatch(f){const s=SPEC[f.kind];f.alive=false;const base=Math.round(f.size*s.base)+(s.id==='kiss'&&f.size>=23?100:0)+(f.giant?500:0);trip.push({kind:f.kind,name:f.giant?'幻の大ギス':s.name,icon:s.icon,size:f.size,points:base,giant:f.giant});data.total++;const prev=data.catalog[s.id]||{count:0,max:0};data.catalog[s.id]={count:prev.count+1,max:Math.max(prev.max,f.size)};if(s.id==='kiss')kissCount++;return base}
function triggerFever(school){if(!school||school.triggered||school.members.filter(f=>f.alive).length<2)return;school.triggered=true;school.feverUntil=elapsed+15;fever=15;say('爆釣タイム！ 15秒間アタリが連続！',true,2.2);sound(1020,.16)}
function land(){if(!fishOn){setPhase('idle');return}const school=fishOn.school,second=doubleFish;let base=recordCatch(fishOn),count=1;if(second&&second.alive){base+=recordCatch(second);count++}combo++;maxCombo=Math.max(maxCombo,combo);const multi=combo>=4?2:combo===3?1.5:combo===2?1.2:1,earned=Math.round(base*multi),bonus=earned-base+(count===2?150:0);score+=base+bonus;bonusTotal+=bonus;if(kissCount>=3&&!missionDone){missionDone=true;missionBonus=300;score+=300}$('#score').textContent=score.toLocaleString();$('#missionHud').textContent=`目標：キス ${Math.min(3,kissCount)}/3匹`;$('#comboBanner').textContent=combo>=2?`FEVER ×${multi} · ${combo}連続ヒット！`:'+'+earned+'点';$('#comboBanner').classList.remove('hidden');const latest=trip.slice(-count).map(f=>`${f.name} ${f.size.toFixed(1)}cm`).join(' ＆ ');say(`${latest} +${earned+(count===2?150:0)+(missionDone&&kissCount===3?300:0)}点`,combo>=2||trip[trip.length-1].giant,2.1);fishOn=null;doubleFish=null;fishTarget=null;setPhase('landed');landHold=1.2;save();if(training&&!firstCatch){firstCatch=true;data.tutorialDone=true;save();training=false;tutorial('');say('初めての1匹！ 次から通常ルールだよ！',true,2.3)}if(school&&school.feverUntil>elapsed)fever=Math.max(fever,school.feverUntil-elapsed);sound(940,.16);buzz([35,40,35])}
function over(){if(phase==='over')return;const finishedMode=mode;setPhase('over');if(Number.isFinite(round)){round=0;$('#clock').textContent='0:00'}const key=bestKey(),old=data.best[key]||0,isNew=score>old;if(isNew)data.best[key]=score;save();const rows=trip.map(f=>`<div class="catch-item"><span class="icon">${f.icon}</span><span class="detail"><b>${f.name} ${f.size.toFixed(1)}cm</b><br><small>${f.giant?'幻の30cm超え！':SPEC[f.kind].rarity}</small></span><b>+${f.points}</b></div>`).join('');const rivalResult=finishedMode==='free'?'':`<p>坂本 ${rivalScore.toLocaleString()}点 / ${score>rivalScore?'坂本に勝利！':score===rivalScore?'引き分け':'坂本の勝利！'}</p>`;$('#resultCard').innerHTML=`<div class="eyebrow">FISHING RESULT</div><h2>🎣 本日の釣果</h2><div class="center"><div class="score-large">${score.toLocaleString()} 点</div>${isNew?'<div class="record">🏆 自己ベスト更新！</div>':''}<p>${trip.length}匹 / キス ${kissCount}匹 / ベスト ${Number(data.best[key]||0).toLocaleString()}点</p>${rivalResult}</div><div class="mission">${missionDone?'🎖️ ミッション達成 +300点':'🎯 キス3匹ミッション '+kissCount+'/3匹'}${finishedMode==='daily'?' / 同じ初期配置 '+dateKey:''}<br>連続ヒット最大 ${maxCombo} / コンボ・ダブルボーナス +${bonusTotal}点</div><div class="catch-list">${rows||'<p>今回はボウズ。魚探で群れを探そう。</p>'}</div><div class="row-buttons"><button class="primary" id="againBtn">もう一度！</button><button class="secondary" id="homeBtn">モード選択</button></div>`;$('#resultOverlay').classList.remove('hidden');$('#againBtn').addEventListener('click',start);$('#homeBtn').addEventListener('click',showMenu);sound(440,.15)}
let maxCombo=0;function showMenu(){cancelHold();$('#resultOverlay').classList.add('hidden');$('#catalogOverlay').classList.add('hidden');training=false;tutorial('');setPhase('menu');menuSync();$('#startOverlay').classList.remove('hidden');last=performance.now()}$('#menuBtn').addEventListener('click',showMenu);$('#finishBtn').addEventListener('click',()=>{if(mode==='free'&&phase!=='menu'&&phase!=='over')over()});
function showCatalog(){cancelHold();$('#catalogGrid').innerHTML=SPEC.map(s=>{const item=data.catalog[s.id],known=!!item;return `<div class="species-card ${known?'':'locked'}"><div class="fish-icon">${known?s.icon:'❔'}</div><b>${known?s.name:'？？？'}</b><small>${known?s.rarity:'まだ釣っていない'}</small><small>${known?`釣果 ${item.count}匹 / 最大 ${item.max.toFixed(1)}cm`:'？？？'}</small>${s.id==='kiss'&&item?.max>=30?'<strong class="giant-badge">🏆 幻の30cm達成！</strong>':''}</div>`}).join('');$('#catalogTotal').textContent=`累計 ${data.total}匹　図鑑 ${SPEC.filter(s=>data.catalog[s.id]?.count>0).length}/${SPEC.length} 種類`;$('#catalogOverlay').classList.remove('hidden');last=performance.now()}$('#catalogBtn').addEventListener('click',showCatalog);$('#closeCatalog').addEventListener('click',()=>{$('#catalogOverlay').classList.add('hidden');last=performance.now()});
function update(dt){anim+=dt;if(phase==='menu'||phase==='over'||!$('#catalogOverlay').classList.contains('hidden'))return;elapsed+=dt;if(Number.isFinite(round)){round=Math.max(0,round-dt);const sec=Math.ceil(round);$('#clock').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(!round){over();return}}if(mode!=='free'){rivalClock-=dt;if(rivalClock<=0){rivalScore+=Math.round(85+rand()*180+(rand()<.13?210:0));$('#rivalScore').textContent=rivalScore.toLocaleString();rivalClock=16+rand()*8}}
sonarReady=Math.max(0,sonarReady-dt);sonarUntil=Math.max(0,sonarUntil-dt);sonarTextUntil=Math.max(0,sonarTextUntil-dt);sonar.disabled=sonarReady>0;$('#sonarLabel').textContent=sonarReady>0?Math.ceil(sonarReady)+'秒':'魚探';sonar.classList.toggle('ready',sonarReady<=0);if(!sonarTextUntil&&!sonarUntil)$('#radar').innerHTML=phase==='fight'?'🎣 魚とファイト中<small>赤なら離して！</small>':`📡 距離 ${Math.round(rig.d)}m<small>${phase==='search'?'巻いて止めて誘おう':'魚探で群れを見つけよう'}</small>`;
for(const s of schools){s.center+=s.speed*dt;if(s.center<s.origin-9||s.center>s.origin+9||s.center<12||s.center>97){s.speed*=-1;s.center=clamp(s.center,12,97)}s.members.forEach(f=>{if(!f.alive)return;f.phase+=dt*(.9+f.v*.3);f.scared=Math.max(0,f.scared-dt);if(f.scared>0){f.d=clamp(f.d+dt*f.v*1.8,5,99);return}if(f===fishTarget||f===fishOn||f===doubleFish)return;const home=clamp(s.center+f.offset+Math.sin(f.phase)*.6,5,99);const near=['search','nibble','bite'].includes(phase)&&Math.abs(rig.d-f.d)<9;const target=near?rig.d:home;const speed=near?(held?.4:1.4)*attract*f.v:f.v*.8;f.d+=clamp(target-f.d,-speed*dt,speed*dt)})}
if(mode==='free'&&fishes.filter(f=>f.alive).length<8){schools=schools.filter(s=>s.members.some(f=>f.alive));fishes=fishes.filter(f=>f.alive);addSchool(20+rand()*72,3+Math.floor(rand()*3))}fever=Math.max(0,fever-dt);if(phase==='idle'&&held){charge+=chargeDir*dt*.73;if(charge>=1){charge=1;chargeDir=-1}else if(charge<=0){charge=0;chargeDir=1}guide()}
else if(phase==='casting'){rig.flight+=dt;const t=clamp(rig.flight/1.03,0,1);rig.d=rig.targetD*t;rig.x=toX(rig.d);rig.y=rig.startY+(ground(rig.targetD)-rig.startY)*t-Math.sin(Math.PI*t)*H*.23;if(t>=1){rig.d=rig.targetD;rig.y=H*.38;rig.flight=0;setPhase('sinking')}}
else if(phase==='sinking'){rig.y+=dt*H*.56;if(rig.y>=ground(rig.d)){rig.y=ground(rig.d);setPhase('search');say('着底！ 巻いて止めて魚を誘おう',false,1.3);sound(230,.07);const school=schools.find(s=>Math.abs(s.center-rig.d)<=4&&s.members.filter(f=>f.alive).length>=2);if(school)triggerFever(school)}}
else if(phase==='search'){attract=Math.max(1,attract-dt*.13);if(held){rig.d=Math.max(1,rig.d-dt*8.4);rig.x=toX(rig.d);rig.y=ground(rig.d)}const school=schools.find(s=>Math.abs(s.center-rig.d)<3&&s.members.filter(f=>f.alive).length>=2);if(school&&!school.triggered&&castIndex>0)triggerFever(school);const f=nearestFish();if(f&&Math.abs(f.d-rig.d)<(fever>0?3:1.8)){waitTime+=dt*(held?.58:1.5)*attract*(fever>0?2.7:1);if(waitTime>(training?.25:.43)){fishTarget=f;nibbleTime=fever>0?.25:.48+rand()*.35;setPhase('nibble');say('コツ…コツ…！ まだ待て！',false,1.1);sound(315,.05);buzz([20,90,20]);if(training)tutorial('⑤ コツコツは待って、ブルブルッ！でタップ！');waitTime=0}}else waitTime=Math.max(0,waitTime-dt*.3);if(rig.d<=1){setPhase('idle');rig.d=0;waitTime=0;say('次の群れを狙おう！',false,1)}}
else if(phase==='nibble'){nibbleTime-=dt;if(nibbleTime<=0){biteTime=training?2.5:fever>0?1.65:1.35;setPhase('bite');say('ブルブルッ！！ 今だ！',true,biteTime);sound(670,.08);buzz([50,40,65])}}
else if(phase==='bite'){biteTime-=dt;if(biteTime<=0){if(fishTarget){fishTarget.scared=4;fishTarget.d=clamp(fishTarget.d+4,5,98)}fishTarget=null;combo=0;setPhase('search');say('あっ、遅かった！',false,1);sound(180,.15)}}
else if(phase==='fight'){fishRun+=dt;const burst=Math.sin(fishRun*(fishOn?.giant?5.2:3.1))>.76?(fishOn?.giant?.39:.26):0,pull=.10+burst+(doubleFish?.11:0)+(fishOn?.giant?.09:0);fightT=clamp(fightT+dt*(pull+(held?.47:-.44)),0,1.11);if(held&&fightT>.12&&fightT<.91){rig.d=Math.max(0,rig.d-dt*(11.5+(1-fightT)*2));rig.x=toX(rig.d);rig.y=ground(rig.d)-4}slackTime=fightT<.1?slackTime+dt:0;$('#tensionNeedle').style.left=clamp(fightT*100,0,100)+'%';$('#tensionText').textContent=fightT>.87?'危険！離せ！':fightT<.21?'ゆるい！巻け！':burst?'魚が走った！':'安全';if(fightT>=1.02)flee('糸が切れた！！');else if(slackTime>.85)flee('糸が緩んでバレた！');else if(rig.d<=.5)land()}
else if(phase==='landed'){landHold-=dt;if(landHold<=0){setPhase('idle');rig.d=0;rig.x=toX(0);waitTime=0;menuSync();guide();$('#comboBanner').classList.add('hidden');say('次はどの群れを狙う？',false,1.1)}}}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);ctx.fill()}function path(p,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();p.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke()}
function paint(){if(!W||!H)return;const theme=THEMES[timeMode],surf=H*.31;let sky=ctx.createLinearGradient(0,0,0,surf);sky.addColorStop(0,theme.sky[0]);sky.addColorStop(1,theme.sky[1]);ctx.fillStyle=sky;ctx.fillRect(0,0,W,surf);let sea=ctx.createLinearGradient(0,surf,0,H);sea.addColorStop(0,theme.sea[0]);sea.addColorStop(1,theme.sea[1]);ctx.fillStyle=sea;ctx.fillRect(0,surf,W,H-surf);ellipse(W*.78,surf*.34,Math.max(10,H*.04),Math.max(10,H*.04),'#ffe5a9');ctx.globalAlpha=.4;for(let k=0;k<5;k++)path(Array.from({length:Math.ceil(W/20)+1},(_,i)=>[i*20,surf+9+k*14+Math.sin(i*.8+k+anim*.9)*2]),'#dcf8fa',1.1);ctx.globalAlpha=1;ctx.beginPath();ctx.moveTo(0,bed(0));for(let x=0;x<=W+8;x+=8)ctx.lineTo(x,bed(fromX(x)));ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();ctx.fillStyle='#e4cea0';ctx.fill();ctx.strokeStyle='#fff2c8';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#c7bfb0';ctx.beginPath();ctx.moveTo(0,surf*.8);ctx.lineTo(W*.15,surf*.99);ctx.lineTo(W*.13,bed(0));ctx.lineTo(0,bed(0)+7);ctx.closePath();ctx.fill();const scale=clamp(H/460,.62,1.15);ctx.save();ctx.translate(W*.085,surf*.87);ctx.scale(scale,scale);path([[0,-20],[0,8],[11,32]],'#1e4050',5);path([[0,8],[-13,30]],'#1e4050',5);ellipse(0,-28,9,9,'#1e4050');path([[0,-11],[20,3],[65,-40]],'#1e4050',4);path([[19,3],[74,-36]],'#714932',3);ctx.restore();
if(phase==='idle'||phase==='menu'){const x=toX(aim);ctx.setLineDash([4,5]);path([[x,surf+12],[x,ground(aim)]],'#ffffffa8');ctx.setLineDash([]);ellipse(x,ground(aim),8,3,'#fff2a7aa');ctx.textAlign='center';ctx.font='900 11px system-ui';ctx.fillStyle='#fff';ctx.fillText(`🎯 ${aim}m`,clamp(x,32,W-32),surf+16)}
for(const s of schools){const members=s.members.filter(f=>f.alive);if(!members.length)continue;const x=toX(members.reduce((sum,f)=>sum+f.d,0)/members.length),pulse=6+Math.sin(anim*2)*2;ctx.strokeStyle=s.feverUntil>elapsed?'#ffe86b':'#e9ffffa3';ctx.lineWidth=s.feverUntil>elapsed?3:1.4;ctx.beginPath();ctx.ellipse(x,surf+8,pulse+(s.feverUntil>elapsed?8:0),3,0,0,Math.PI*2);ctx.stroke();if(s.feverUntil>elapsed){ctx.fillStyle='#fff5b2';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.fillText(`爆釣 ${Math.ceil(s.feverUntil-elapsed)}秒`,x,surf+29)}}
const searching=['search','nibble','bite','fight'].includes(phase);for(const f of fishes){if(!f.alive)continue;if(!(sonarUntil>0||searching&&Math.abs(f.d-rig.d)<17))continue;const x=toX(f.d),y=ground(f.d)-11-Math.sin(f.phase)*3,sz=clamp(W/450,.55,1)*(.8+f.size/35)*(f.giant?1.35:1);ctx.save();ctx.globalAlpha=sonarUntil>0?.9:.46;ctx.translate(x,y);ctx.scale(sz,sz);ellipse(0,0,11,4.5,f.giant?'#ffe16c':SPEC[f.kind].color);ctx.fillStyle=f.giant?'#ffe16c':SPEC[f.kind].color;ctx.beginPath();ctx.moveTo(-8,0);ctx.lineTo(-17,-5);ctx.lineTo(-17,5);ctx.closePath();ctx.fill();ellipse(6,-1,1,1,'#12394a');ctx.restore();if(sonarUntil>0||f.giant){ctx.strokeStyle=f.giant?'#ffe16c':'#adfff3a0';ctx.beginPath();ctx.arc(x,y,9+Math.sin(anim*6)*2,0,Math.PI*2);ctx.stroke()}}
if(!['idle','menu','over','landed'].includes(phase)){const tipX=W*.085+74*scale,tipY=surf*.87-36*scale;path([[tipX,tipY],[rig.x,rig.y]],'#fcffffdd',1.4);ellipse(rig.x,rig.y,4.5,6,'#56616a');path([[rig.x,rig.y],[rig.x+13,rig.y+2]],'#f4ebcb',1);ellipse(rig.x+15,rig.y+2,3,2.5,'#ff8c66');if(fishOn)ellipse(rig.x+20,rig.y-5,fishOn.giant?19:13,fishOn.giant?8:5,fishOn.giant?'#ffe16c':SPEC[fishOn.kind].color)}ctx.fillStyle='#ffffffcc';ctx.textAlign='center';ctx.font='800 10px system-ui';for(let d=0;d<=100;d+=20){const x=toX(d);if(x>10&&x<W-10)ctx.fillText(d+'m',x,bed(d)+25)}if(!['idle','menu','over'].includes(phase)){ctx.textAlign='right';ctx.fillStyle='white';ctx.fillText(`仕掛け ${Math.round(rig.d)}m`,W-9,surf-7)}}
function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(document.visibilityState!=='hidden'){update(dt);paint()}if(messageUntil&&now/1000>messageUntil){hint.classList.remove('visible','alert');messageUntil=0}requestAnimationFrame(frame)}window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.visibilityState==='hidden')cancelHold()});menuSync();resize();guide();requestAnimationFrame(frame);
})();